export type Phrase = {
  id: string
  hanzi: string
  pinyin: string
  portuguese: string
  literal: string
  note: string
  tonePattern: string
  emoji?: string
  category?: 'greeting' | 'farewell' | 'family' | 'politeness' | 'question' | 'place' | 'action' | 'person' | 'time' | 'food'
}

export type Lesson = {
  id: string
  unitId: string
  title: string
  focus: string
  xp: number
  minutes: number
  phrases: Phrase[]
  reviewPhraseIds?: string[]
  curiosity?: string
}

export type Unit = {
  id: string
  title: string
  level: string
  accent: 'red' | 'jade' | 'gold' | 'ink'
  summary: string
  lessonIds: string[]
}

export type ClipSeed = {
  id: string
  title: string
  source: string
  level: string
  theme: string
  url: string
  kind: 'article' | 'video' | 'song'
}

export type StudyMoment = {
  id: string
  title: string
  source: string
  type: 'meme' | 'song' | 'anthem' | 'history'
  level: string
  phrase: string
  pinyin: string
  meaning: string
  note: string
  searchUrl: string
}

export type StrokeHint = {
  x: number
  y: number
  arrow: '↓' | '↑' | '←' | '→' | '↗' | '↘' | '↙' | '↖' | '•'
}

export type WritingCharacter = {
  id: string
  character: string
  pinyin: string
  meaning: string
  strokes: number
  radical: string
  words: string[]
  strokeOrder: string[]
  strokeHints?: StrokeHint[]
  curiosity?: string
}

export type Chunk = {
  id: string
  unitId?: Unit['id']
  hanzi: string
  pinyin: string
  portuguese: string
  gloss: string
  blank: string
  blankAnswer: string
  note: string
}

export const units: Unit[] = [
  {
    id: 'tones',
    title: 'Nadando na lagoa',
    level: 'Fase 1',
    accent: 'red',
    summary: 'O carpa testa a agua: som, ritmo, tons e primeiras silabas.',
    lessonIds: ['tones-hello', 'tones-four', 'tones-initials', 'tones-finals-family'],
  },
  {
    id: 'survival',
    title: 'Subindo o rio',
    level: 'Fase 2',
    accent: 'jade',
    summary: 'Cumprimentos, agradecimentos e respostas curtas para nao se perder na correnteza.',
    lessonIds: ['survival-greetings', 'survival-politeness', 'survival-questions', 'survival-places'],
  },
  {
    id: 'numbers',
    title: 'Cachoeira do Dragao',
    level: 'Fase 3',
    accent: 'gold',
    summary: 'Contar, perguntar preco e pedir coisas para nao parar antes da cachoeira.',
    lessonIds: ['numbers-basic', 'numbers-money', 'numbers-order', 'numbers-time'],
  },
  {
    id: 'daily',
    title: 'Saltando o Portao',
    level: 'Fase 4',
    accent: 'ink',
    summary: 'Familia, tempo, comida e rotinas: o ultimo salto antes de virar dragao.',
    lessonIds: ['daily-family', 'daily-food', 'daily-time', 'daily-feelings'],
  },
  {
    id: 'people',
    title: 'Ponte dos Pronomes',
    level: 'Fase 5',
    accent: 'red',
    summary: 'Eu, voce, ele, ela, nos e perguntas sobre pessoas.',
    lessonIds: ['people-pronouns', 'people-family', 'people-roles'],
  },
  {
    id: 'school',
    title: 'Casa do Estudo',
    level: 'Fase 6',
    accent: 'jade',
    summary: 'Chines, livro, professor, estudante e a rotina de aprender.',
    lessonIds: ['school-language', 'school-classroom', 'school-actions'],
  },
  {
    id: 'city',
    title: 'Mercado de Jade',
    level: 'Fase 7',
    accent: 'gold',
    summary: 'Ir, vir, comprar, lojas, transporte e lugares da cidade.',
    lessonIds: ['city-going', 'city-transport', 'city-shopping'],
  },
  {
    id: 'sky',
    title: 'Ceu das Horas',
    level: 'Fase 8',
    accent: 'ink',
    summary: 'Dias da semana, clima, agora, gostar e saber fazer.',
    lessonIds: ['sky-week', 'sky-weather', 'sky-ability'],
  },
  {
    id: 'hsk1-gate',
    title: 'Portao HSK1',
    level: 'Fase 9',
    accent: 'red',
    summary: 'Mini-dialogos de prova: nome, nacionalidade, idade e moradia.',
    lessonIds: ['gate-name', 'gate-origin-age', 'gate-home-check'],
  },
]

export const lessons: Lesson[] = [
  {
    id: 'tones-hello',
    unitId: 'tones',
    title: 'Ola sem tropeçar nos tons',
    focus: 'Tons 3-3, saudacao basica',
    xp: 18,
    minutes: 6,
    phrases: [
      { id: 'ni-hao', hanzi: '你好', pinyin: 'nǐ hǎo', portuguese: 'ola', literal: 'voce bom', note: 'Na fala natural o primeiro terceiro tom sobe para soar mais leve.', tonePattern: '3-3', emoji: '👋', category: 'greeting' },
      { id: 'ni-hao-ma-greet', hanzi: '你好吗', pinyin: 'nǐ hǎo ma', portuguese: 'voce esta bem?', literal: 'voce bom (pergunta)', note: 'A particula 吗 transforma o cumprimento em pergunta de status.', tonePattern: '3-3-0', emoji: '🤔', category: 'question' },
      { id: 'wo-hen-hao', hanzi: '我很好', pinyin: 'wǒ hěn hǎo', portuguese: 'eu estou bem', literal: 'eu muito bom', note: 'hen suaviza; nem sempre significa "muito" nesse contexto.', tonePattern: '3-3-3', emoji: '😊', category: 'greeting' },
      { id: 'ni-ne', hanzi: '你呢？', pinyin: 'nǐ ne?', portuguese: 'e voce?', literal: 'voce e (devolver)', note: '呢 devolve a pergunta sem repetir o verbo.', tonePattern: '3-0', emoji: '🫵', category: 'question' },
      { id: 'ye-hao', hanzi: '也好', pinyin: 'yě hǎo', portuguese: 'tambem estou bem', literal: 'tambem bom', note: '也 + adjetivo concorda com o que foi dito antes.', tonePattern: '3-3', emoji: '👍', category: 'greeting' },
    ],
  },
  {
    id: 'tones-four',
    unitId: 'tones',
    title: 'Quatro tons, uma silaba',
    focus: 'ma nos tons 1, 2, 3 e 4 + pares minimos',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['ni-hao', 'wo-hen-hao'],
    phrases: [
      { id: 'ma-tones', hanzi: '妈 麻 马 骂', pinyin: 'mā má mǎ mà', portuguese: 'mae, canhamo, cavalo, xingar', literal: 'quatro tons com ma', note: 'A mesma silaba muda de significado quando o tom muda.', tonePattern: '1-2-3-4' },
      { id: 'shi-tones', hanzi: '是 十 事', pinyin: 'shì shí shì', portuguese: 'ser, dez, assunto', literal: 'sons parecidos, tons diferentes', note: 'Ouvir pares minimos ajuda a separar significado por tom.', tonePattern: '4-2-4' },
      { id: 'mai-mai', hanzi: '买 卖', pinyin: 'mǎi mài', portuguese: 'comprar / vender', literal: 'comprar vender', note: 'Mesmo radical, mesmo som: so o tom diferencia comprar (3) de vender (4).', tonePattern: '3-4' },
      { id: 'wo-shi-mama', hanzi: '我是妈妈', pinyin: 'wǒ shì māma', portuguese: 'eu sou a mae', literal: 'eu ser mae', note: 'Encadeia tom 3 → 4 → 1+0; bom para treinar transicoes.', tonePattern: '3-4-1-0' },
      { id: 'ni-ma-hao-ma', hanzi: '你妈好吗', pinyin: 'nǐ mā hǎo ma', portuguese: 'sua mae esta bem?', literal: 'voce mae bem (pergunta)', note: 'Tom 3 inicial vira meio-tom porque vem antes de outro tom 3.', tonePattern: '3-1-3-0' },
    ],
  },
  {
    id: 'tones-initials',
    unitId: 'tones',
    title: 'Iniciais que confundem',
    focus: 'zh, ch, sh, r retroflexos',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['ma-tones', 'shi-tones'],
    phrases: [
      { id: 'zhong-guo', hanzi: '中国', pinyin: 'Zhōngguó', portuguese: 'China', literal: 'pais do meio', note: 'zh tem a lingua enrolada para tras, diferente de z.', tonePattern: '1-2', emoji: '🇨🇳', category: 'place' },
      { id: 'ren', hanzi: '人', pinyin: 'rén', portuguese: 'pessoa', literal: 'pessoa', note: 'O r em mandarim fica entre r, zh e um som mais retroflexo.', tonePattern: '2', emoji: '🧑', category: 'person' },
      { id: 'chi-fan-quick', hanzi: '吃饭', pinyin: 'chī fàn', portuguese: 'comer', literal: 'comer arroz', note: 'ch e a versao "soprada" de zh; aspira mais ar.', tonePattern: '1-4', emoji: '🍚', category: 'action' },
      { id: 'lao-shi', hanzi: '老师', pinyin: 'lǎoshī', portuguese: 'professor(a)', literal: 'velho mestre', note: 'sh e a inicial mais retroflexa; nao confundir com s.', tonePattern: '3-1', emoji: '👩‍🏫', category: 'person' },
      { id: 'ri-ben', hanzi: '日本', pinyin: 'Rìběn', portuguese: 'Japao', literal: 'origem do sol', note: 'r aqui e quase um zh suave com vibracao na ponta da lingua.', tonePattern: '4-3', emoji: '🇯🇵', category: 'place' },
      { id: 'shen-me-shi-hou', hanzi: '什么时候', pinyin: 'shénme shíhou', portuguese: 'quando?', literal: 'que momento', note: 'Pratica: sh-r-sh em sequencia, mantenha a lingua atras dos dentes.', tonePattern: '2-0-2-0', emoji: '⏰', category: 'question' },
    ],
  },
  {
    id: 'tones-finals-family',
    unitId: 'tones',
    title: 'Finais com voz clara',
    focus: 'a, ao, ang e tom neutro',
    xp: 20,
    minutes: 6,
    reviewPhraseIds: ['zhong-guo', 'ren'],
    phrases: [
      { id: 'ba-ba', hanzi: '爸爸', pinyin: 'bàba', portuguese: 'pai', literal: 'pai', note: 'A segunda silaba fica leve; nao vire tom forte de novo.', tonePattern: '4-0', emoji: '👨', category: 'family' },
      { id: 'ma-ma', hanzi: '妈妈', pinyin: 'māma', portuguese: 'mae', literal: 'mae', note: 'Repita devagar e depois natural; segundo ma curto.', tonePattern: '1-0', emoji: '👩', category: 'family' },
      { id: 'ge-ge', hanzi: '哥哥', pinyin: 'gēge', portuguese: 'irmao mais velho', literal: 'irmao irmao', note: 'Padrao de duplicacao familiar com tom neutro no fim.', tonePattern: '1-0', emoji: '👦', category: 'family' },
      { id: 'jie-jie', hanzi: '姐姐', pinyin: 'jiějie', portuguese: 'irma mais velha', literal: 'irma irma', note: 'jie tem ditongo i+e; mantenha a transicao curta.', tonePattern: '3-0', emoji: '👧', category: 'family' },
      { id: 'pang-pang', hanzi: '胖胖', pinyin: 'pàngpang', portuguese: 'gordinho (apelido carinhoso)', literal: 'gordinho', note: 'A final ang e nasalizada — som vem do nariz, nao da garganta.', tonePattern: '4-0', emoji: '😄', category: 'family' },
    ],
  },
  {
    id: 'survival-greetings',
    unitId: 'survival',
    title: 'Cumprimentos reais',
    focus: 'ola, boa noite, ate logo',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['ni-hao', 'chi-fan-quick'],
    phrases: [
      { id: 'zao-shang-hao', hanzi: '早上好', pinyin: 'zǎoshang hǎo', portuguese: 'bom dia', literal: 'manha boa', note: 'Usado pela manha; ni hao funciona o dia todo.', tonePattern: '3-0-3', emoji: '🌅', category: 'greeting' },
      { id: 'wan-shang-hao', hanzi: '晚上好', pinyin: 'wǎnshang hǎo', portuguese: 'boa noite (cumprimento)', literal: 'noite boa', note: 'Cumprimento, nao despedida; para "tchau a noite" use 晚安.', tonePattern: '3-0-3', emoji: '🌙', category: 'greeting' },
      { id: 'wan-an', hanzi: '晚安', pinyin: 'wǎn ān', portuguese: 'boa noite (despedida)', literal: 'noite paz', note: 'Diz quando alguem vai dormir.', tonePattern: '3-1', emoji: '😴', category: 'farewell' },
      { id: 'zai-jian', hanzi: '再见', pinyin: 'zàijiàn', portuguese: 'tchau', literal: 'ver de novo', note: 'Formal o suficiente para quase qualquer contexto.', tonePattern: '4-4', emoji: '🤚', category: 'farewell' },
      { id: 'hui-jian', hanzi: '回见', pinyin: 'huíjiàn', portuguese: 'ate mais', literal: 'voltar ver', note: 'Mais informal que 再见; usado entre amigos.', tonePattern: '2-4', emoji: '✌️', category: 'farewell' },
      { id: 'huan-ying', hanzi: '欢迎', pinyin: 'huānyíng', portuguese: 'bem-vindo', literal: 'alegremente receber', note: 'Frequente em lojas, hoteis e dialogos formais.', tonePattern: '1-2', emoji: '🎉', category: 'greeting' },
    ],
  },
  {
    id: 'survival-politeness',
    unitId: 'survival',
    title: 'Educacao rapida',
    focus: 'obrigado, desculpa, por favor',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['ni-hao', 'zai-jian'],
    phrases: [
      { id: 'xie-xie', hanzi: '谢谢', pinyin: 'xièxie', portuguese: 'obrigado', literal: 'agradecer', note: 'A segunda silaba fica mais leve.', tonePattern: '4-0', emoji: '🙏', category: 'politeness' },
      { id: 'bu-ke-qi', hanzi: '不客气', pinyin: 'bú kèqi', portuguese: 'de nada', literal: 'nao seja cerimonioso', note: 'Resposta padrao a 谢谢.', tonePattern: '2-4-0', emoji: '😌', category: 'politeness' },
      { id: 'dui-bu-qi', hanzi: '对不起', pinyin: 'duìbuqǐ', portuguese: 'desculpa', literal: 'nao consigo te encarar', note: 'Pedido de desculpas firme; mais forte que 不好意思.', tonePattern: '4-0-3', emoji: '😔', category: 'politeness' },
      { id: 'mei-guan-xi', hanzi: '没关系', pinyin: 'méi guānxi', portuguese: 'sem problema', literal: 'nao tem relacao', note: 'Resposta natural para desculpas ou pequenos erros.', tonePattern: '2-1-0', emoji: '🤷', category: 'politeness' },
      { id: 'qing', hanzi: '请', pinyin: 'qǐng', portuguese: 'por favor', literal: 'pedir', note: 'Sozinho ou colado em verbos: 请坐 (sente-se), 请说 (fale).', tonePattern: '3', emoji: '🙇', category: 'politeness' },
      { id: 'bu-hao-yi-si', hanzi: '不好意思', pinyin: 'bù hǎoyìsi', portuguese: 'desculpa, com licenca', literal: 'sem boa intencao', note: 'Mais leve que 对不起; bom para desculpa pequena ou abordar alguem.', tonePattern: '4-3-4-0', emoji: '😅', category: 'politeness' },
    ],
  },
  {
    id: 'survival-questions',
    unitId: 'survival',
    title: 'Perguntas pequenas',
    focus: 'particula 吗 e palavras-pergunta',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['xie-xie', 'ni-hao-ma-greet'],
    phrases: [
      { id: 'ni-hao-ma', hanzi: '你好吗？', pinyin: 'nǐ hǎo ma?', portuguese: 'voce esta bem?', literal: 'voce bom pergunta', note: 'ma transforma uma afirmacao em pergunta sim/nao.', tonePattern: '3-3-0', emoji: '🤔', category: 'question' },
      { id: 'shen-me', hanzi: '什么？', pinyin: 'shénme?', portuguese: 'o que?', literal: 'que coisa', note: 'Uma das palavras de pergunta mais frequentes.', tonePattern: '2-0', emoji: '❓', category: 'question' },
      { id: 'shei', hanzi: '谁？', pinyin: 'shéi?', portuguese: 'quem?', literal: 'quem', note: 'Substitui a pessoa desconhecida; ocupa o lugar do nome.', tonePattern: '2', emoji: '👤', category: 'question' },
      { id: 'na-li', hanzi: '哪里？', pinyin: 'nǎli?', portuguese: 'onde?', literal: 'qual lugar', note: 'Use junto com 在: 在哪里 → onde fica.', tonePattern: '3-0', emoji: '📍', category: 'question' },
      { id: 'wei-shen-me', hanzi: '为什么？', pinyin: 'wèishénme?', portuguese: 'por que?', literal: 'por que coisa', note: 'Pergunta por motivo. Resposta usa 因为...', tonePattern: '4-2-0', emoji: '💭', category: 'question' },
      { id: 'shi-bu-shi', hanzi: '是不是', pinyin: 'shì bu shì', portuguese: 'e ou nao e?', literal: 'ser nao ser', note: 'Estrutura V-不-V: forma compacta de fazer pergunta de confirmacao.', tonePattern: '4-0-4', emoji: '⚖️', category: 'question' },
    ],
  },
  {
    id: 'survival-places',
    unitId: 'survival',
    title: 'Nao se perder',
    focus: 'perguntar com educacao e achar lugares',
    xp: 24,
    minutes: 8,
    reviewPhraseIds: ['dui-bu-qi', 'qing'],
    phrases: [
      { id: 'qing-wen', hanzi: '请问', pinyin: 'qǐngwèn', portuguese: 'com licenca', literal: 'por favor perguntar', note: 'Use antes de perguntas para soar educado com desconhecidos.', tonePattern: '3-4', emoji: '🙋', category: 'politeness' },
      { id: 'ce-suo-zai-na-li', hanzi: '厕所在哪里？', pinyin: 'cèsuǒ zài nǎli?', portuguese: 'onde fica o banheiro?', literal: 'banheiro estar onde', note: '在哪里 e um bloco pronto para perguntar onde algo fica.', tonePattern: '4-3-4-3-0', emoji: '🚻', category: 'place' },
      { id: 'chu-kou', hanzi: '出口', pinyin: 'chūkǒu', portuguese: 'saida', literal: 'sair boca', note: 'Placa universal em estacoes, lojas e metros.', tonePattern: '1-3', emoji: '🚪', category: 'place' },
      { id: 'ru-kou', hanzi: '入口', pinyin: 'rùkǒu', portuguese: 'entrada', literal: 'entrar boca', note: 'Par com 出口; mesma estrutura.', tonePattern: '4-3', emoji: '🏠', category: 'place' },
      { id: 'zai-zhe-li', hanzi: '在这里', pinyin: 'zài zhèli', portuguese: 'aqui', literal: 'estar este lugar', note: 'Resposta tipica para 在哪里; troque 这 por 那 para "ali".', tonePattern: '4-4-0', emoji: '📍', category: 'place' },
      { id: 'ting-yi-xia', hanzi: '听一下', pinyin: 'tīng yíxià', portuguese: 'escuta um pouco', literal: 'ouvir um momento', note: '一下 amacia o pedido; usado para chamar atencao educadamente.', tonePattern: '1-2-4', emoji: '👂', category: 'action' },
    ],
  },
  {
    id: 'numbers-basic',
    unitId: 'numbers',
    title: 'Numeros 1 a 10',
    focus: 'contagem e reconhecimento auditivo',
    xp: 20,
    minutes: 6,
    reviewPhraseIds: ['ni-hao', 'xie-xie'],
    phrases: [
      { id: 'yi-er-san', hanzi: '一 二 三', pinyin: 'yī èr sān', portuguese: 'um, dois, tres', literal: '1 2 3', note: 'yi muda de tom em combinacoes, mas memorize o som base primeiro.', tonePattern: '1-4-1' },
      { id: 'si-wu-liu', hanzi: '四 五 六', pinyin: 'sì wǔ liù', portuguese: 'quatro, cinco, seis', literal: '4 5 6', note: 'si exige a lingua atras dos dentes — som de "ss" sem vogal forte.', tonePattern: '4-3-4' },
      { id: 'qi-ba-jiu', hanzi: '七 八 九', pinyin: 'qī bā jiǔ', portuguese: 'sete, oito, nove', literal: '7 8 9', note: 'qi soa quase como "tchi"; q nao e c pesado.', tonePattern: '1-1-3' },
      { id: 'shi', hanzi: '十', pinyin: 'shí', portuguese: 'dez', literal: '10', note: 'Subida do tom 2 — quase como uma pergunta curta.', tonePattern: '2' },
      { id: 'shi-yi', hanzi: '十一', pinyin: 'shíyī', portuguese: 'onze', literal: 'dez um', note: 'A formula 10+N gera 11-19; 11 = 十一, 12 = 十二.', tonePattern: '2-1' },
      { id: 'er-shi', hanzi: '二十', pinyin: 'èrshí', portuguese: 'vinte', literal: 'dois dez', note: 'A formula N×10: 20 = 二十, 30 = 三十.', tonePattern: '4-2' },
    ],
  },
  {
    id: 'numbers-money',
    unitId: 'numbers',
    title: 'Quanto custa?',
    focus: 'preco, demonstrativos e barganha',
    xp: 24,
    minutes: 8,
    reviewPhraseIds: ['yi-er-san', 'na-li'],
    phrases: [
      { id: 'duo-shao-qian', hanzi: '多少钱？', pinyin: 'duōshao qián?', portuguese: 'quanto custa?', literal: 'quanto dinheiro', note: 'Frase pronta para lojas, mercados e taxis.', tonePattern: '1-0-2' },
      { id: 'zhe-ge', hanzi: '这个', pinyin: 'zhège', portuguese: 'este', literal: 'este item', note: 'Muito usado apontando para algo que voce quer.', tonePattern: '4-0' },
      { id: 'na-ge', hanzi: '那个', pinyin: 'nàge', portuguese: 'aquele', literal: 'aquele item', note: 'Par com 这个; aponta para algo mais distante.', tonePattern: '4-0' },
      { id: 'tai-gui-le', hanzi: '太贵了', pinyin: 'tài guì le', portuguese: 'esta caro demais', literal: 'muito caro mudanca', note: 'Use para barganhar; 了 enfatiza a constatacao.', tonePattern: '4-4-0' },
      { id: 'pian-yi-yi-dian', hanzi: '便宜一点', pinyin: 'piányi yìdiǎn', portuguese: 'um pouco mais barato', literal: 'barato um pouco', note: 'Pedido educado para baixar o preco.', tonePattern: '2-0-4-3' },
      { id: 'wu-shi-kuai', hanzi: '五十块', pinyin: 'wǔshí kuài', portuguese: 'cinquenta yuans', literal: 'cinquenta moeda', note: '块 e o classificador coloquial para yuan; em escrita formal usa-se 元.', tonePattern: '3-2-4' },
    ],
  },
  {
    id: 'numbers-order',
    unitId: 'numbers',
    title: 'Pedir no balcao',
    focus: 'quero, uma unidade, classificadores',
    xp: 24,
    minutes: 8,
    reviewPhraseIds: ['duo-shao-qian', 'zhe-ge'],
    phrases: [
      { id: 'wo-yao', hanzi: '我要', pinyin: 'wǒ yào', portuguese: 'eu quero', literal: 'eu querer', note: 'Funciona para pedidos diretos; com educacao adicione 请.', tonePattern: '3-4' },
      { id: 'yi-bei-shui', hanzi: '一杯水', pinyin: 'yì bēi shuǐ', portuguese: 'um copo de agua', literal: 'um copo agua', note: '杯 e o classificador para copos e bebidas.', tonePattern: '4-1-3' },
      { id: 'yi-ge-ren', hanzi: '一个人', pinyin: 'yí ge rén', portuguese: 'uma pessoa', literal: 'um (cl) pessoa', note: '个 e o classificador coringa quando voce esquece o especifico.', tonePattern: '2-0-2' },
      { id: 'liang-ge-cha', hanzi: '两个茶', pinyin: 'liǎng ge chá', portuguese: 'dois chas', literal: 'dois (cl) cha', note: 'Para "2" antes de classificador, use 两 e nao 二.', tonePattern: '3-0-2' },
      { id: 'wo-yao-zhe-ge', hanzi: '我要这个', pinyin: 'wǒ yào zhège', portuguese: 'eu quero este', literal: 'eu querer este', note: 'Combinacao mais usada apontando para o cardapio ou produto.', tonePattern: '3-4-4-0' },
      { id: 'qing-gei-wo', hanzi: '请给我', pinyin: 'qǐng gěi wǒ', portuguese: 'me de, por favor', literal: 'por favor dar eu', note: '请给我 + objeto: forma educada de pedir.', tonePattern: '3-3-3' },
    ],
  },
  {
    id: 'numbers-time',
    unitId: 'numbers',
    title: 'Horario sem travar',
    focus: 'horas, agora e amanha',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['wo-yao', 'shi'],
    phrases: [
      { id: 'san-dian', hanzi: '三点', pinyin: 'sān diǎn', portuguese: 'tres horas', literal: 'tres ponto', note: '点 marca horas cheias: 三点 = tres horas.', tonePattern: '1-3' },
      { id: 'ming-tian-shi-dian', hanzi: '明天十点', pinyin: 'míngtiān shí diǎn', portuguese: 'amanha as dez', literal: 'amanha dez horas', note: 'O tempo (manha/amanha) vem antes do horario.', tonePattern: '2-1-2-3' },
      { id: 'xian-zai-ji-dian', hanzi: '现在几点？', pinyin: 'xiànzài jǐ diǎn?', portuguese: 'que horas sao agora?', literal: 'agora quantas horas', note: '几 pergunta numero baixo (1-9). 现在 fixa o tempo.', tonePattern: '4-4-3-3' },
      { id: 'ban', hanzi: '半', pinyin: 'bàn', portuguese: 'meia', literal: 'metade', note: '七点半 = sete e meia. Vai depois do 点.', tonePattern: '4' },
      { id: 'shang-wu', hanzi: '上午', pinyin: 'shàngwǔ', portuguese: 'manha (10h-12h)', literal: 'cima meio-dia', note: 'Use antes do horario: 上午十点 = dez da manha.', tonePattern: '4-3' },
      { id: 'xia-wu', hanzi: '下午', pinyin: 'xiàwǔ', portuguese: 'tarde', literal: 'baixo meio-dia', note: 'Par com 上午; 下午三点 = tres da tarde.', tonePattern: '4-3' },
    ],
  },
  {
    id: 'daily-family',
    unitId: 'daily',
    title: 'Familia perto',
    focus: 'casa, irmaos e relacoes proximas',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['ba-ba', 'ma-ma'],
    phrases: [
      { id: 'wo-de-jia', hanzi: '我的家', pinyin: 'wǒ de jiā', portuguese: 'minha familia / minha casa', literal: 'eu possessivo casa', note: 'jia pode ser casa ou familia dependendo do contexto.', tonePattern: '3-0-1' },
      { id: 'peng-you', hanzi: '朋友', pinyin: 'péngyou', portuguese: 'amigo', literal: 'amigo', note: 'A segunda silaba e neutra na fala comum.', tonePattern: '2-0' },
      { id: 'di-di', hanzi: '弟弟', pinyin: 'dìdi', portuguese: 'irmao mais novo', literal: 'irmao novo', note: 'Mandarim distingue irmao mais velho/novo, diferente do portugues.', tonePattern: '4-0' },
      { id: 'mei-mei', hanzi: '妹妹', pinyin: 'mèimei', portuguese: 'irma mais nova', literal: 'irma nova', note: 'Par com 弟弟; mesma estrutura.', tonePattern: '4-0' },
      { id: 'jia-ren', hanzi: '家人', pinyin: 'jiārén', portuguese: 'familiares', literal: 'casa pessoa', note: 'Coletivo: 我的家人 = minha familia (as pessoas).', tonePattern: '1-2' },
    ],
  },
  {
    id: 'daily-food',
    unitId: 'daily',
    title: 'Comida do dia a dia',
    focus: 'comer, beber, classificadores de comida',
    xp: 24,
    minutes: 8,
    reviewPhraseIds: ['chi-fan-quick', 'wo-yao-zhe-ge'],
    phrases: [
      { id: 'chi-fan', hanzi: '吃饭', pinyin: 'chī fàn', portuguese: 'comer / fazer refeicao', literal: 'comer arroz', note: 'Chifan virou uma expressao geral para fazer uma refeicao.', tonePattern: '1-4' },
      { id: 'he-shui', hanzi: '喝水', pinyin: 'hē shuǐ', portuguese: 'beber agua', literal: 'beber agua', note: 'h em he e aspirado, com ar saindo claro.', tonePattern: '1-3' },
      { id: 'mi-fan', hanzi: '米饭', pinyin: 'mǐfàn', portuguese: 'arroz cozido', literal: 'graos arroz', note: 'Diferente de 饭 sozinho, que pode ser refeicao em geral.', tonePattern: '3-4' },
      { id: 'mian-tiao', hanzi: '面条', pinyin: 'miàntiáo', portuguese: 'macarrao', literal: 'massa fios', note: 'Classificador 一碗 (uma tigela) e o usual.', tonePattern: '4-2' },
      { id: 'cha', hanzi: '茶', pinyin: 'chá', portuguese: 'cha', literal: 'cha', note: 'Som "tchá"; nao confundir com "ts" do z.', tonePattern: '2' },
      { id: 'hao-chi', hanzi: '好吃', pinyin: 'hǎochī', portuguese: 'gostoso (comida)', literal: 'bom comer', note: 'Para bebida o equivalente e 好喝 (hǎohē).', tonePattern: '3-1' },
      { id: 'wo-e-le', hanzi: '我饿了', pinyin: 'wǒ è le', portuguese: 'estou com fome', literal: 'eu fome mudanca', note: 'O 了 marca que a fome chegou agora.', tonePattern: '3-4-0' },
    ],
  },
  {
    id: 'daily-time',
    unitId: 'daily',
    title: 'Hoje, agora, amanha',
    focus: 'tempo do dia e marcadores',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['san-dian', 'xie-xie'],
    phrases: [
      { id: 'jin-tian', hanzi: '今天', pinyin: 'jīntiān', portuguese: 'hoje', literal: 'este dia', note: 'j exige a lingua mais alta, perto do som "tji".', tonePattern: '1-1' },
      { id: 'ming-tian', hanzi: '明天', pinyin: 'míngtiān', portuguese: 'amanha', literal: 'dia claro', note: 'Util para combinar horarios simples.', tonePattern: '2-1' },
      { id: 'zuo-tian', hanzi: '昨天', pinyin: 'zuótiān', portuguese: 'ontem', literal: 'dia passado', note: 'Forma o trio com hoje/amanha; treine os tres juntos.', tonePattern: '2-1' },
      { id: 'xian-zai', hanzi: '现在', pinyin: 'xiànzài', portuguese: 'agora', literal: 'agora estar', note: 'Marca temporal mais comum em frases de horario.', tonePattern: '4-4' },
      { id: 'yi-hou', hanzi: '以后', pinyin: 'yǐhòu', portuguese: 'depois', literal: 'apos', note: 'Frase: 以后见 = ate mais tarde.', tonePattern: '3-4' },
    ],
  },
  {
    id: 'daily-feelings',
    unitId: 'daily',
    title: 'Corpo e energia',
    focus: 'sentimentos basicos, cansaco, fome',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['wo-hen-hao', 'mei-guan-xi'],
    phrases: [
      { id: 'wo-lei-le', hanzi: '我累了', pinyin: 'wǒ lèi le', portuguese: 'estou cansado', literal: 'eu cansado mudanca', note: '了 marca que o estado mudou: agora estou cansado.', tonePattern: '3-4-0' },
      { id: 'wo-xiang-xiu-xi', hanzi: '我想休息', pinyin: 'wǒ xiǎng xiūxi', portuguese: 'quero descansar', literal: 'eu querer descansar', note: '想 suaviza o pedido e funciona bem antes de verbos.', tonePattern: '3-3-1-0' },
      { id: 'wo-gao-xing', hanzi: '我很高兴', pinyin: 'wǒ hěn gāoxìng', portuguese: 'estou feliz', literal: 'eu muito alto-animo', note: '很 antes de adjetivo e quase obrigatorio em frase afirmativa.', tonePattern: '3-3-1-4' },
      { id: 'wo-bing-le', hanzi: '我病了', pinyin: 'wǒ bìng le', portuguese: 'estou doente', literal: 'eu doente mudanca', note: 'Mesma estrutura de 我累了 — adjetivo + 了 = mudanca de estado.', tonePattern: '3-4-0' },
      { id: 'mei-shi', hanzi: '没事', pinyin: 'méi shì', portuguese: 'nao foi nada / tudo bem', literal: 'nao tem assunto', note: 'Resposta tipica quando alguem pergunta se voce esta bem.', tonePattern: '2-4' },
    ],
  },
  {
    id: 'people-pronouns',
    unitId: 'people',
    title: 'Quem esta falando?',
    focus: 'pronomes pessoais e plural',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['ni-hao', 'xie-xie'],
    phrases: [
      { id: 'ta-shi-shei', hanzi: '他是谁？', pinyin: 'tā shì shéi?', portuguese: 'quem e ele?', literal: 'ele ser quem', note: '谁 pergunta sobre pessoa. Troque 他 por 她 para falar dela.', tonePattern: '1-4-2' },
      { id: 'ta-shi-wo-pengyou', hanzi: '她是我朋友', pinyin: 'tā shì wǒ péngyou', portuguese: 'ela e minha amiga', literal: 'ela ser eu amiga', note: 'Em fala simples, 我朋友 funciona como "minha amiga" sem 的.', tonePattern: '1-4-3-2-0' },
      { id: 'wo-men', hanzi: '我们', pinyin: 'wǒmen', portuguese: 'nos', literal: 'eu plural', note: 'O sufixo 们 marca plural em pronomes humanos: 你们, 他们.', tonePattern: '3-0' },
      { id: 'ni-men-hao', hanzi: '你们好', pinyin: 'nǐmen hǎo', portuguese: 'ola, voces', literal: 'voces bom', note: 'Cumprimento para mais de uma pessoa.', tonePattern: '3-0-3' },
      { id: 'ta-men-shi', hanzi: '他们是', pinyin: 'tāmen shì', portuguese: 'eles sao', literal: 'eles ser', note: '他们 cobre grupo misto ou so masculino; 她们 e exclusivamente feminino.', tonePattern: '1-0-4' },
    ],
  },
  {
    id: 'people-family',
    unitId: 'people',
    title: 'Familia perto de voce',
    focus: 'familia, pai, mae, todos',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['ba-ba', 'peng-you'],
    phrases: [
      { id: 'wo-ai-wo-de-jia', hanzi: '我爱我的家', pinyin: 'wǒ ài wǒ de jiā', portuguese: 'eu amo minha familia', literal: 'eu amar minha casa/familia', note: '爱 e direto; 家 pode ser casa ou familia pelo contexto.', tonePattern: '3-4-3-0-1' },
      { id: 'ba-ma-dou-hao', hanzi: '爸爸妈妈都好', pinyin: 'bàba māma dōu hǎo', portuguese: 'papai e mamae estao bem', literal: 'pai mae todos bem', note: '都 marca que a ideia vale para todos no grupo.', tonePattern: '4-0-1-0-1-3' },
      { id: 'ye-ye', hanzi: '爷爷', pinyin: 'yéye', portuguese: 'avo (pai do pai)', literal: 'avo paterno', note: 'O sistema chines distingue avos paternos e maternos.', tonePattern: '2-0' },
      { id: 'nai-nai', hanzi: '奶奶', pinyin: 'nǎinai', portuguese: 'avo (mae do pai)', literal: 'avo paterna', note: 'Par com 爷爷.', tonePattern: '3-0' },
      { id: 'wo-you-yi-ge-mei-mei', hanzi: '我有一个妹妹', pinyin: 'wǒ yǒu yí ge mèimei', portuguese: 'eu tenho uma irma mais nova', literal: 'eu ter um (cl) irma-nova', note: '有 expressa posse; com pessoas use 个 como classificador.', tonePattern: '3-3-2-0-4-0' },
    ],
  },
  {
    id: 'people-roles',
    unitId: 'people',
    title: 'Professor e estudante',
    focus: 'profissao escolar basica',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['lao-shi', 'ba-ba'],
    phrases: [
      { id: 'ta-shi-laoshi', hanzi: '他是老师', pinyin: 'tā shì lǎoshī', portuguese: 'ele e professor', literal: 'ele ser professor', note: '老师 e uma das primeiras palavras sociais do HSK1.', tonePattern: '1-4-3-1' },
      { id: 'wo-shi-xuesheng', hanzi: '我是学生', pinyin: 'wǒ shì xuésheng', portuguese: 'eu sou estudante', literal: 'eu ser estudante', note: '学生 tem segunda silaba leve na fala natural.', tonePattern: '3-4-2-0' },
      { id: 'yi-sheng', hanzi: '医生', pinyin: 'yīshēng', portuguese: 'medico', literal: 'medico', note: 'Apareceu no HSK1. Estrutura: 我是医生 = sou medico.', tonePattern: '1-1' },
      { id: 'ni-shi-shenme', hanzi: '你是什么工作？', pinyin: 'nǐ shì shénme gōngzuò?', portuguese: 'qual e o seu trabalho?', literal: 'voce ser que trabalho', note: 'Pergunta direta sobre profissao, comum em apresentacoes.', tonePattern: '3-4-2-0-1-4' },
      { id: 'wo-bu-shi', hanzi: '我不是', pinyin: 'wǒ bú shì', portuguese: 'eu nao sou', literal: 'eu nao ser', note: '不 vira 2o tom (bú) antes de tom 4 (shì).', tonePattern: '3-2-4' },
    ],
  },
  {
    id: 'school-language',
    unitId: 'school',
    title: 'Abrindo o livro de chines',
    focus: 'estudar, chines, falar',
    xp: 24,
    minutes: 8,
    reviewPhraseIds: ['zhong-guo', 'ni-hao-ma-greet'],
    phrases: [
      { id: 'wo-xuexi-zhongwen', hanzi: '我学习中文', pinyin: 'wǒ xuéxí Zhōngwén', portuguese: 'eu estudo chines', literal: 'eu estudar lingua chinesa', note: '学习 e o verbo base para estudar; 中文 e a lingua chinesa.', tonePattern: '3-2-2-1-2' },
      { id: 'ni-hui-shuo-zhongwen-ma', hanzi: '你会说中文吗？', pinyin: 'nǐ huì shuō Zhōngwén ma?', portuguese: 'voce sabe falar chines?', literal: 'voce saber falar chines pergunta', note: '会 fala de habilidade: saber/conseguir fazer algo.', tonePattern: '3-4-1-1-2-0' },
      { id: 'han-yu', hanzi: '汉语', pinyin: 'Hànyǔ', portuguese: 'lingua chinesa (han)', literal: 'lingua dos han', note: 'Sinonimo academico de 中文; usados quase indistintamente.', tonePattern: '4-3' },
      { id: 'ying-yu', hanzi: '英语', pinyin: 'Yīngyǔ', portuguese: 'ingles', literal: 'lingua inglesa', note: 'Mesma estrutura: 西班牙语 = espanhol, 葡萄牙语 = portugues.', tonePattern: '1-3' },
      { id: 'wo-bu-dong', hanzi: '我不懂', pinyin: 'wǒ bù dǒng', portuguese: 'eu nao entendo', literal: 'eu nao entender', note: 'Frase salva-vidas em qualquer dialogo.', tonePattern: '3-4-3' },
      { id: 'qing-zai-shuo', hanzi: '请再说一遍', pinyin: 'qǐng zài shuō yí biàn', portuguese: 'fale de novo, por favor', literal: 'por favor de novo falar uma vez', note: '一遍 = uma vez; padrao para pedir repeticao.', tonePattern: '3-4-1-2-4' },
    ],
  },
  {
    id: 'school-classroom',
    unitId: 'school',
    title: 'Coisas da sala',
    focus: 'livro, mesa, computador, posicao',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['wo-xuexi-zhongwen', 'zhe-ge'],
    phrases: [
      { id: 'zhe-shi-wo-de-shu', hanzi: '这是我的书', pinyin: 'zhè shì wǒ de shū', portuguese: 'este e meu livro', literal: 'isto ser meu livro', note: '这是... apresenta objetos de forma simples.', tonePattern: '4-4-3-0-1' },
      { id: 'diannao-zai-zhuozi-shang', hanzi: '电脑在桌子上', pinyin: 'diànnǎo zài zhuōzi shàng', portuguese: 'o computador esta em cima da mesa', literal: 'computador estar mesa em cima', note: '在 + lugar localiza coisas; 上 marca "em cima".', tonePattern: '4-3-4-1-0-4' },
      { id: 'yi', hanzi: '椅子', pinyin: 'yǐzi', portuguese: 'cadeira', literal: 'cadeira', note: 'Combine: 椅子在桌子前 (cadeira esta em frente a mesa).', tonePattern: '3-0' },
      { id: 'bi', hanzi: '笔', pinyin: 'bǐ', portuguese: 'caneta / lapis', literal: 'instrumento de escrita', note: 'Vale para qualquer instrumento de escrita; 铅笔 = lapis especifico.', tonePattern: '3' },
      { id: 'shou-ji', hanzi: '手机', pinyin: 'shǒujī', portuguese: 'celular', literal: 'mao maquina', note: 'Bem util: 我的手机 = meu celular.', tonePattern: '3-1' },
    ],
  },
  {
    id: 'school-actions',
    unitId: 'school',
    title: 'Ler, escrever, escutar',
    focus: 'verbos de estudo',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['han-yu', 'qing'],
    phrases: [
      { id: 'wo-kan-shu', hanzi: '我看书', pinyin: 'wǒ kàn shū', portuguese: 'eu leio livro', literal: 'eu olhar livro', note: '看 cobre ver/olhar/ler dependendo do objeto.', tonePattern: '3-4-1' },
      { id: 'qing-xie-hanzi', hanzi: '请写汉字', pinyin: 'qǐng xiě hànzì', portuguese: 'por favor escreva hanzi', literal: 'por favor escrever caracteres chineses', note: '请 deixa o comando educado; 写 e escrever.', tonePattern: '3-3-4-4' },
      { id: 'ting-yin-yue', hanzi: '听音乐', pinyin: 'tīng yīnyuè', portuguese: 'ouvir musica', literal: 'ouvir musica', note: '听 e o verbo geral de ouvir.', tonePattern: '1-1-4' },
      { id: 'kan-dian-shi', hanzi: '看电视', pinyin: 'kàn diànshì', portuguese: 'assistir TV', literal: 'olhar eletro-ver', note: 'Combine 看 + meio: 看书 (livro), 看电视 (TV), 看电影 (cinema).', tonePattern: '4-4-4' },
      { id: 'shuo-hua', hanzi: '说话', pinyin: 'shuōhuà', portuguese: 'conversar', literal: 'falar fala', note: 'Verbo "neutro" para conversar; nao precisa objeto.', tonePattern: '1-4' },
    ],
  },
  {
    id: 'city-going',
    unitId: 'city',
    title: 'Ir e vir pela cidade',
    focus: 'ir, vir, perto, longe',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['na-li', 'jin-tian'],
    phrases: [
      { id: 'wo-qu-xuexiao', hanzi: '我去学校', pinyin: 'wǒ qù xuéxiào', portuguese: 'eu vou para a escola', literal: 'eu ir escola', note: '去 + lugar: estrutura limpa para destino.', tonePattern: '3-4-2-4' },
      { id: 'ta-lai-zhongguo', hanzi: '他来中国', pinyin: 'tā lái Zhōngguó', portuguese: 'ele vem para a China', literal: 'ele vir China', note: '来 = movimento vindo para perto do falante/contexto.', tonePattern: '1-2-1-2' },
      { id: 'jin', hanzi: '近', pinyin: 'jìn', portuguese: 'perto', literal: 'perto', note: 'Use com 离: A 离 B 很近 = A esta perto de B.', tonePattern: '4' },
      { id: 'yuan', hanzi: '远', pinyin: 'yuǎn', portuguese: 'longe', literal: 'longe', note: 'Par com 近.', tonePattern: '3' },
      { id: 'wo-jia-li-zhe-li-jin', hanzi: '我家离这里很近', pinyin: 'wǒ jiā lí zhèli hěn jìn', portuguese: 'minha casa fica perto daqui', literal: 'minha casa de aqui muito perto', note: '离 + ponto B + adjetivo de distancia.', tonePattern: '3-1-2-4-0-3-4' },
    ],
  },
  {
    id: 'city-transport',
    unitId: 'city',
    title: 'Taxi, trem e caminho',
    focus: 'transporte e direcao',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['wo-qu-xuexiao', 'ce-suo-zai-na-li'],
    phrases: [
      { id: 'wo-zuo-chuzuche', hanzi: '我坐出租车', pinyin: 'wǒ zuò chūzūchē', portuguese: 'eu vou de taxi', literal: 'eu sentar taxi', note: '坐 e usado para transporte: sentar/pegar um veiculo.', tonePattern: '3-4-1-1-1' },
      { id: 'huochezhan-zai-nali', hanzi: '火车站在哪里？', pinyin: 'huǒchēzhàn zài nǎli?', portuguese: 'onde fica a estacao de trem?', literal: 'estacao de trem estar onde', note: '在哪里 reaparece: troque o lugar e a pergunta continua pronta.', tonePattern: '3-1-4-4-3-0' },
      { id: 'gong-jiao-che', hanzi: '公交车', pinyin: 'gōngjiāochē', portuguese: 'onibus', literal: 'publico-transporte-veiculo', note: 'Tambem 公交; 我坐公交车 = pego o onibus.', tonePattern: '1-1-1' },
      { id: 'fei-ji', hanzi: '飞机', pinyin: 'fēijī', portuguese: 'aviao', literal: 'voar maquina', note: '坐飞机 = pegar aviao.', tonePattern: '1-1' },
      { id: 'kai-che', hanzi: '开车', pinyin: 'kāichē', portuguese: 'dirigir', literal: 'abrir veiculo', note: 'Para dirigir use 开车, nao 坐.', tonePattern: '1-1' },
    ],
  },
  {
    id: 'city-shopping',
    unitId: 'city',
    title: 'Comprar no mercado',
    focus: 'loja, comprar, fruta, dinheiro',
    xp: 24,
    minutes: 8,
    reviewPhraseIds: ['duo-shao-qian', 'wo-yao'],
    phrases: [
      { id: 'shangdian-you-shui', hanzi: '商店有水', pinyin: 'shāngdiàn yǒu shuǐ', portuguese: 'a loja tem agua', literal: 'loja ter agua', note: '有 marca existencia/posse: tem, ha.', tonePattern: '1-4-3-3' },
      { id: 'wo-yao-mai-shuiguo', hanzi: '我要买水果', pinyin: 'wǒ yào mǎi shuǐguǒ', portuguese: 'eu quero comprar frutas', literal: 'eu querer comprar fruta', note: '买 e comprar; 水果 junta agua+fruto, mas significa fruta.', tonePattern: '3-4-3-3-3' },
      { id: 'mai-le', hanzi: '卖了', pinyin: 'mài le', portuguese: 'vendeu / acabou', literal: 'vender (concluido)', note: 'Em loja: 卖完了 = esgotou.', tonePattern: '4-0' },
      { id: 'ping-guo', hanzi: '苹果', pinyin: 'píngguǒ', portuguese: 'maca', literal: 'maca', note: 'Substantivo concreto util pra praticar classificadores: 一个苹果.', tonePattern: '2-3' },
      { id: 'you-mei-you', hanzi: '有没有？', pinyin: 'yǒu méi yǒu?', portuguese: 'tem ou nao tem?', literal: 'ter nao ter', note: 'V-不-V (aqui V-没-V para 有): pergunta de confirmacao.', tonePattern: '3-2-3' },
      { id: 'duo-shao', hanzi: '多少', pinyin: 'duōshao', portuguese: 'quanto / quantos', literal: 'muito pouco', note: 'Para numero indefinido. Para 1-9, prefira 几.', tonePattern: '1-0' },
    ],
  },
  {
    id: 'sky-week',
    unitId: 'sky',
    title: 'Semana e agora',
    focus: 'dias da semana e marcadores',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['jin-tian', 'xian-zai'],
    phrases: [
      { id: 'jintian-xingqi-yi', hanzi: '今天星期一', pinyin: 'jīntiān xīngqī yī', portuguese: 'hoje e segunda-feira', literal: 'hoje semana um', note: '星期 + numero (1-6) forma os dias; domingo e 星期天.', tonePattern: '1-1-1-1-1' },
      { id: 'xianzai-ba-dian', hanzi: '现在八点', pinyin: 'xiànzài bā diǎn', portuguese: 'agora sao oito horas', literal: 'agora oito horas', note: '现在 coloca a frase no presente imediato.', tonePattern: '4-4-1-3' },
      { id: 'xing-qi-tian', hanzi: '星期天', pinyin: 'xīngqītiān', portuguese: 'domingo', literal: 'semana ceu', note: 'Tambem 星期日 (mais formal/escrito).', tonePattern: '1-1-1' },
      { id: 'zhou-mo', hanzi: '周末', pinyin: 'zhōumò', portuguese: 'fim de semana', literal: 'semana fim', note: '周末快乐 = bom fim de semana.', tonePattern: '1-4' },
      { id: 'mei-tian', hanzi: '每天', pinyin: 'měitiān', portuguese: 'todo dia', literal: 'cada dia', note: '每天 + verbo: 每天学中文 (estudo chines todo dia).', tonePattern: '3-1' },
    ],
  },
  {
    id: 'sky-weather',
    unitId: 'sky',
    title: 'Clima simples',
    focus: 'clima, chuva, quente, frio',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['jintian-xingqi-yi', 'wo-hen-hao'],
    phrases: [
      { id: 'tianqi-hen-hao', hanzi: '天气很好', pinyin: 'tiānqì hěn hǎo', portuguese: 'o tempo esta bom', literal: 'tempo muito bom', note: '天气 e clima; 很 suaviza adjetivos.', tonePattern: '1-4-3-3' },
      { id: 'xianzai-xia-yu', hanzi: '现在下雨', pinyin: 'xiànzài xià yǔ', portuguese: 'agora esta chovendo', literal: 'agora cair chuva', note: '下雨 e o bloco comum para chover.', tonePattern: '4-4-4-3' },
      { id: 'leng', hanzi: '冷', pinyin: 'lěng', portuguese: 'frio', literal: 'frio', note: '今天很冷 = hoje esta frio.', tonePattern: '3' },
      { id: 're', hanzi: '热', pinyin: 'rè', portuguese: 'quente / calor', literal: 'quente', note: 'Par com 冷; descreve clima ou temperatura.', tonePattern: '4' },
      { id: 'feng-da', hanzi: '风很大', pinyin: 'fēng hěn dà', portuguese: 'esta ventando muito', literal: 'vento muito grande', note: '大 cobre intensidade de vento, chuva, neve, etc.', tonePattern: '1-3-4' },
    ],
  },
  {
    id: 'sky-ability',
    unitId: 'sky',
    title: 'Gosto e habilidade',
    focus: 'gostar, saber fazer, um pouco',
    xp: 22,
    minutes: 7,
    reviewPhraseIds: ['ni-hui-shuo-zhongwen-ma', 'tianqi-hen-hao'],
    phrases: [
      { id: 'ke-yi', hanzi: '可以', pinyin: 'kěyǐ', portuguese: 'pode (permissao)', literal: 'poder', note: 'Use 可以 para pedir permissao; 我可以... ma? = posso...?', tonePattern: '3-3' },
      { id: 'bu-hui', hanzi: '不会', pinyin: 'bú huì', portuguese: 'nao sei (fazer)', literal: 'nao habilidade', note: 'Resposta a 你会...吗? para dizer que nao sabe.', tonePattern: '2-4' },
      {
        id: 'wo-hui-shuo-yidian-zhongwen',
        hanzi: '我会说一点中文',
        pinyin: 'wǒ huì shuō yìdiǎn Zhōngwén',
        portuguese: 'eu sei falar um pouco de chines',
        literal: 'eu saber falar um pouco chines',
        note: '一点 deixa a frase humilde: um pouco.',
        tonePattern: '3-4-1-4-3-1-2',
      },
      {
        id: 'wo-xihuan-he-cha',
        hanzi: '我喜欢喝茶',
        pinyin: 'wǒ xǐhuan hē chá',
        portuguese: 'eu gosto de beber cha',
        literal: 'eu gostar beber cha',
        note: '喜欢 + verbo/objeto expressa preferencia.',
        tonePattern: '3-3-0-1-2',
      },
      { id: 'wo-bu-xihuan', hanzi: '我不喜欢', pinyin: 'wǒ bù xǐhuan', portuguese: 'eu nao gosto', literal: 'eu nao gostar', note: 'Negativa direta; complete com objeto: 我不喜欢咖啡.', tonePattern: '3-4-3-0' },
      { id: 'hen-xi-huan', hanzi: '很喜欢', pinyin: 'hěn xǐhuan', portuguese: 'gosto muito', literal: 'muito gostar', note: 'Versao reforcada de 喜欢; soa natural em respostas curtas.', tonePattern: '3-3-0' },
    ],
  },
  {
    id: 'gate-name',
    unitId: 'hsk1-gate',
    title: 'Checkpoint: nome',
    focus: 'dialogo de apresentacao completo',
    xp: 28,
    minutes: 9,
    reviewPhraseIds: ['ni-hao', 'xie-xie'],
    phrases: [
      { id: 'ni-jiao-shenme-mingzi', hanzi: '你叫什么名字？', pinyin: 'nǐ jiào shénme míngzi?', portuguese: 'qual e o seu nome?', literal: 'voce chamar que nome', note: '叫什么名字 e pergunta padrao de apresentacao.', tonePattern: '3-4-2-0-2-0' },
      { id: 'wo-jiao-kauan', hanzi: '我叫卡蓝', pinyin: 'wǒ jiào Kǎlán', portuguese: 'me chamo Kauan', literal: 'eu chamar Kauan', note: 'Troque 卡蓝 pelo seu nome chines ou transliterado.', tonePattern: '3-4-3-2' },
      { id: 'ren-shi-ni-hen-gao-xing', hanzi: '认识你很高兴', pinyin: 'rènshi nǐ hěn gāoxìng', portuguese: 'prazer em conhece-lo', literal: 'conhecer voce muito feliz', note: 'Frase formal pos-apresentacao; reflexo: 我也是 (eu tambem).', tonePattern: '4-0-3-3-1-4' },
      { id: 'qing-jiao-wo', hanzi: '请叫我', pinyin: 'qǐng jiào wǒ', portuguese: 'me chame de', literal: 'por favor chamar eu', note: 'Para indicar apelido: 请叫我小卡 = me chame de "pequeno Ka".', tonePattern: '3-4-3' },
      { id: 'ni-de-ming-zi-zen-me-xie', hanzi: '你的名字怎么写？', pinyin: 'nǐ de míngzi zěnme xiě?', portuguese: 'como se escreve o seu nome?', literal: 'seu nome como escrever', note: '怎么 + verbo = como se faz tal acao.', tonePattern: '3-0-2-0-3-0-3' },
      { id: 'xing', hanzi: '姓', pinyin: 'xìng', portuguese: 'sobrenome', literal: 'sobrenome', note: '我姓王 = meu sobrenome e Wang. Importante para apresentacoes formais.', tonePattern: '4' },
      { id: 'gui-xing', hanzi: '您贵姓？', pinyin: 'nín guì xìng?', portuguese: 'qual seu sobrenome? (formal)', literal: 'voce nobre sobrenome', note: '您 e a forma respeitosa de 你; usado com mais velhos e desconhecidos.', tonePattern: '2-4-4' },
    ],
  },
  {
    id: 'gate-origin-age',
    unitId: 'hsk1-gate',
    title: 'Checkpoint: origem e idade',
    focus: 'pais, idade, anos',
    xp: 28,
    minutes: 9,
    reviewPhraseIds: ['ni-jiao-shenme-mingzi', 'ren-shi-ni-hen-gao-xing'],
    phrases: [
      { id: 'ni-shi-na-guo-ren', hanzi: '你是哪国人？', pinyin: 'nǐ shì nǎ guó rén?', portuguese: 'de que pais voce e?', literal: 'voce ser qual pais pessoa', note: '哪国人 pergunta nacionalidade de forma compacta.', tonePattern: '3-4-3-2-2' },
      { id: 'wo-ershi-sui', hanzi: '我二十岁', pinyin: 'wǒ èrshí suì', portuguese: 'eu tenho vinte anos', literal: 'eu vinte anos', note: '岁 marca idade; nao precisa de verbo "ter".', tonePattern: '3-4-2-4' },
      { id: 'wo-shi-baxi-ren', hanzi: '我是巴西人', pinyin: 'wǒ shì Bāxī rén', portuguese: 'eu sou brasileiro', literal: 'eu ser Brasil pessoa', note: 'Pais + 人 = nacionalidade. 中国人, 美国人, 日本人.', tonePattern: '3-4-1-1-2' },
      { id: 'ni-ji-sui', hanzi: '你几岁？', pinyin: 'nǐ jǐ suì?', portuguese: 'quantos anos voce tem? (criancas)', literal: 'voce quantos anos', note: '几 espera numero baixo; para adultos use 多大.', tonePattern: '3-3-4' },
      { id: 'duo-da', hanzi: '你多大？', pinyin: 'nǐ duō dà?', portuguese: 'qual sua idade? (adultos)', literal: 'voce quanto grande', note: '多大 e neutro para adultos sem soar invasivo.', tonePattern: '3-1-4' },
      { id: 'wo-ye-shi', hanzi: '我也是', pinyin: 'wǒ yě shì', portuguese: 'eu tambem sou', literal: 'eu tambem ser', note: '也 vem antes do verbo, nao no fim.', tonePattern: '3-3-4' },
    ],
  },
  {
    id: 'gate-home-check',
    unitId: 'hsk1-gate',
    title: 'Checkpoint: morar',
    focus: 'morar, cidade, lugar, ja',
    xp: 28,
    minutes: 9,
    reviewPhraseIds: ['ni-shi-na-guo-ren', 'wo-jiao-kauan'],
    phrases: [
      { id: 'ni-zhu-zai-nar', hanzi: '你住在哪儿？', pinyin: 'nǐ zhù zài nǎr?', portuguese: 'onde voce mora?', literal: 'voce morar em onde', note: '住在 + lugar monta a frase de moradia. 哪儿 e variante de 哪里.', tonePattern: '3-4-4-3' },
      { id: 'wo-zhu-zai-beijing', hanzi: '我住在北京', pinyin: 'wǒ zhù zài Běijīng', portuguese: 'eu moro em Pequim', literal: 'eu morar em Pequim', note: 'Troque 北京 pela cidade que voce quer dizer.', tonePattern: '3-4-4-3-1' },
      { id: 'ni-zai-zhongguo-duo-jiu', hanzi: '你在中国多久了？', pinyin: 'nǐ zài Zhōngguó duō jiǔ le?', portuguese: 'ha quanto tempo voce esta na China?', literal: 'voce em China quanto tempo (mudanca)', note: '多久 = quanto tempo; o 了 final marca acumulado ate agora.', tonePattern: '3-4-1-2-1-3-0' },
      { id: 'wo-lai-le-yi-nian', hanzi: '我来了一年', pinyin: 'wǒ lái le yì nián', portuguese: 'estou ha um ano', literal: 'eu vir (mudanca) um ano', note: '了 antes do tempo marca duracao acumulada.', tonePattern: '3-2-0-4-2' },
      { id: 'ni-jia-you-ji-ge-ren', hanzi: '你家有几个人？', pinyin: 'nǐ jiā yǒu jǐ ge rén?', portuguese: 'quantas pessoas tem na sua familia?', literal: 'sua casa ter quantos (cl) pessoa', note: 'Pergunta classica de prova oral; resposta: 我家有X个人.', tonePattern: '3-1-3-3-0-2' },
      { id: 'wo-zai-xue-zhongwen', hanzi: '我在学中文', pinyin: 'wǒ zài xué Zhōngwén', portuguese: 'eu estou estudando chines', literal: 'eu (em curso) estudar chines', note: '在 + verbo = acao em progresso (presente continuo).', tonePattern: '3-4-2-1-2' },
      { id: 'mei-cuo', hanzi: '没错', pinyin: 'méi cuò', portuguese: 'isso mesmo / sem erro', literal: 'nao errado', note: 'Resposta confirmando informacao em dialogos formais.', tonePattern: '2-4' },
    ],
  },
]

export const clipSeeds: ClipSeed[] = [
  {
    id: 'pinyin-chart',
    title: 'Tabela de pinyin com audio',
    source: 'Yoyo Chinese',
    level: 'Fundacao',
    theme: 'pinyin',
    kind: 'article',
    url: 'https://yoyochinese.com/chinese-learning-tools/Mandarin-Chinese-pronunciation-lesson/pinyin-chart-table',
  },
  {
    id: 'digmandarin-pinyin',
    title: 'Guia completo de pinyin',
    source: 'DigMandarin',
    level: 'Fundacao',
    theme: 'tons',
    kind: 'article',
    url: 'https://www.digmandarin.com/learn-chinese-pinyin',
  },
  {
    id: 'goeast-pronunciation',
    title: 'Pronuncia e pares minimos',
    source: 'GoEast Mandarin',
    level: 'HSK 1',
    theme: 'pronuncia',
    kind: 'article',
    url: 'https://goeastmandarin.com/chinese-pronunciation/',
  },
  {
    id: 'music-lab',
    title: 'Aprender chines com musica',
    source: 'Chinese with Ping',
    level: 'Livre',
    theme: 'musica',
    kind: 'song',
    url: 'https://www.chinesewithping.com/',
  },
]

export const studyMoments: StudyMoment[] = [
  {
    id: 'super-idol',
    title: 'Super Idol',
    source: 'Meme musical',
    type: 'song',
    level: 'Livre',
    phrase: '笑容',
    pinyin: 'xiàoróng',
    meaning: 'sorriso',
    note: 'Use o meme para treinar xiao, rong e o segundo tom subindo no final.',
    searchUrl: 'https://www.youtube.com/results?search_query=Super+Idol+Chinese+lyrics+learning',
  },
  {
    id: 'john-cena-bing-chilling',
    title: 'John Cena falando mandarim',
    source: 'Meme de entrevista',
    type: 'meme',
    level: 'HSK 1',
    phrase: '冰淇淋',
    pinyin: 'bīngqílín',
    meaning: 'sorvete',
    note: 'Palavra divertida para treinar b, q e tons em sequencia.',
    searchUrl: 'https://www.youtube.com/results?search_query=John+Cena+Mandarin+bing+chilling',
  },
  {
    id: 'chinese-anthem',
    title: 'Hino chines',
    source: 'Musica civica',
    type: 'anthem',
    level: 'Interesse cultural',
    phrase: '起来',
    pinyin: 'qǐlái',
    meaning: 'levantar-se',
    note: 'Boa palavra para perceber terceiro tom seguido de segundo tom.',
    searchUrl: 'https://www.youtube.com/results?search_query=Chinese+national+anthem+lyrics+pinyin',
  },
  {
    id: 'mao-historical-song',
    title: 'Cancoes historicas de Mao Zedong',
    source: 'Contexto historico',
    type: 'history',
    level: 'Cultura',
    phrase: '东方红',
    pinyin: 'Dōngfāng hóng',
    meaning: 'o oriente e vermelho',
    note: 'Use como contexto cultural e para treinar dong, fang e hong sem depender de traducao literal.',
    searchUrl: 'https://www.youtube.com/results?search_query=The+East+is+Red+Chinese+pinyin',
  },
  {
    id: 'football-meme',
    title: 'Meme de torcida',
    source: 'Frase viral',
    type: 'meme',
    level: 'HSK 1',
    phrase: '加油',
    pinyin: 'jiāyóu',
    meaning: 'forca / vamos la',
    note: 'Perfeito para jogos, desafios e rankings entre amigos.',
    searchUrl: 'https://www.youtube.com/results?search_query=jiayou+Chinese+meme',
  },
]

export const allPhrases = lessons.flatMap((lesson) =>
  lesson.phrases.map((phrase) => ({
    ...phrase,
    lessonId: lesson.id,
    lessonTitle: lesson.title,
    unitId: lesson.unitId,
  })),
)

export const toneDrills = [
  {
    id: 'ma',
    title: 'ma em quatro tons',
    hanzi: '妈 麻 马 骂',
    pinyin: 'mā má mǎ mà',
    focus: 'Altura da voz',
  },
  {
    id: 'hao',
    title: 'terceiro tom em sequencia',
    hanzi: '你好 很好',
    pinyin: 'nǐ hǎo, hěn hǎo',
    focus: 'Mudanca do terceiro tom',
  },
  {
    id: 'shi',
    title: 'sh e tons curtos',
    hanzi: '是 十 事',
    pinyin: 'shì shí shì',
    focus: 'Retroflexo e contraste',
  },
]

export const writingCharacters: WritingCharacter[] = [
  {
    id: 'ren',
    character: '人',
    pinyin: 'rén',
    meaning: 'pessoa',
    strokes: 2,
    radical: '人',
    words: ['人', '中国人', '朋友'],
    strokeOrder: ['Traço descendente para a esquerda.', 'Traço descendente para a direita, abrindo a base.'],
    strokeHints: [
      { x: 50, y: 22, arrow: '↙' },
      { x: 50, y: 42, arrow: '↘' },
    ],
    curiosity: '人 parece uma pessoa caminhando: dois tracos seguram o corpo em equilibrio.',
  },
  {
    id: 'kou',
    character: '口',
    pinyin: 'kǒu',
    meaning: 'boca / abertura',
    strokes: 3,
    radical: '口',
    words: ['口', '人口', '门口'],
    strokeOrder: ['Vertical esquerda.', 'Canto superior e vertical direita.', 'Linha inferior fechando o quadrado.'],
    strokeHints: [
      { x: 26, y: 25, arrow: '↓' },
      { x: 26, y: 25, arrow: '→' },
      { x: 26, y: 70, arrow: '→' },
    ],
    curiosity: '口 e a ideia de boca/abertura; ele volta em palavras como porta, saida e entrada.',
  },
  {
    id: 'ni',
    character: '你',
    pinyin: 'nǐ',
    meaning: 'voce',
    strokes: 7,
    radical: '亻',
    words: ['你好', '你们', '你好吗'],
    strokeOrder: [
      'Componente pessoa: traço inclinado curto.',
      'Vertical do componente pessoa.',
      'Pequeno traço inclinado no topo direito.',
      'Gancho horizontal descendo no centro.',
      'Traço vertical com gancho.',
      'Ponto esquerdo.',
      'Ponto direito.',
    ],
    strokeHints: [
      { x: 22, y: 22, arrow: '↙' },
      { x: 22, y: 42, arrow: '↓' },
      { x: 58, y: 22, arrow: '↘' },
      { x: 50, y: 35, arrow: '→' },
      { x: 60, y: 42, arrow: '↓' },
      { x: 52, y: 62, arrow: '•' },
      { x: 68, y: 62, arrow: '•' },
    ],
    curiosity: '你 junta pessoa na esquerda com 尔 na direita: e literalmente a pessoa que esta diante de voce.',
  },
  {
    id: 'hao',
    character: '好',
    pinyin: 'hǎo',
    meaning: 'bom / bem',
    strokes: 6,
    radical: '女',
    words: ['你好', '很好', '好吃'],
    strokeOrder: [
      'Mulher: traço curvo para baixo.',
      'Traço inclinado cruzando.',
      'Horizontal do componente mulher.',
      'Filho: traço horizontal curto.',
      'Gancho vertical.',
      'Horizontal final atravessando o componente filho.',
    ],
    strokeHints: [
      { x: 24, y: 22, arrow: '↘' },
      { x: 14, y: 42, arrow: '↗' },
      { x: 14, y: 60, arrow: '→' },
      { x: 58, y: 22, arrow: '→' },
      { x: 72, y: 22, arrow: '↓' },
      { x: 58, y: 58, arrow: '→' },
    ],
    curiosity: '好 combina mulher 女 e filho 子; na origem, a cena familiar virou a ideia de bom/bem.',
  },
  {
    id: 'zhong',
    character: '中',
    pinyin: 'zhōng',
    meaning: 'meio / China',
    strokes: 4,
    radical: '丨',
    words: ['中国', '中文', '中午'],
    strokeOrder: ['Caixa externa esquerda.', 'Topo e direita da caixa.', 'Base da caixa.', 'Vertical central atravessando.'],
    strokeHints: [
      { x: 33, y: 22, arrow: '↓' },
      { x: 33, y: 22, arrow: '→' },
      { x: 33, y: 60, arrow: '→' },
      { x: 50, y: 12, arrow: '↓' },
    ],
    curiosity: '中 mostra uma linha atravessando o centro: por isso significa meio e aparece em China, 中国.',
  },
  {
    id: 'shui',
    character: '水',
    pinyin: 'shuǐ',
    meaning: 'agua',
    strokes: 4,
    radical: '水',
    words: ['喝水', '一杯水', '水果'],
    strokeOrder: ['Vertical com gancho no centro.', 'Traço descendente esquerdo.', 'Traço curto direito.', 'Traço longo direito.'],
    strokeHints: [
      { x: 50, y: 18, arrow: '↓' },
      { x: 42, y: 42, arrow: '↙' },
      { x: 58, y: 42, arrow: '↘' },
      { x: 60, y: 58, arrow: '↘' },
    ],
    curiosity: '水 nasceu como desenho de correnteza; os pontos laterais lembram agua abrindo caminho.',
  },
]

export const chunks: Chunk[] = [
  {
    id: 'chunk-meu-nome',
    unitId: 'survival',
    hanzi: '我叫卡蓝',
    pinyin: 'wǒ jiào Kǎ-lán',
    portuguese: 'me chamo Kauan',
    gloss: 'eu / chamar / Kauan',
    blank: '我___卡蓝',
    blankAnswer: '叫',
    note: 'Use 叫 (jiào) para apresentar como gosta de ser chamado. Troque o final pelo seu nome.',
  },
  {
    id: 'chunk-tudo-bem',
    unitId: 'survival',
    hanzi: '你好吗',
    pinyin: 'nǐ hǎo ma',
    portuguese: 'tudo bem?',
    gloss: 'voce / bem / (pergunta)',
    blank: '你好___',
    blankAnswer: '吗',
    note: 'A particula 吗 (ma) transforma uma afirmacao em pergunta sim/nao.',
  },
  {
    id: 'chunk-obrigado',
    unitId: 'survival',
    hanzi: '谢谢你',
    pinyin: 'xièxie nǐ',
    portuguese: 'obrigado a voce',
    gloss: 'obrigado / voce',
    blank: '谢谢___',
    blankAnswer: '你',
    note: 'Bloco fixo: 谢谢 vai sempre antes do alvo do agradecimento.',
  },
  {
    id: 'chunk-quanto-custa',
    unitId: 'numbers',
    hanzi: '这个多少钱',
    pinyin: 'zhège duōshao qián',
    portuguese: 'quanto custa isto?',
    gloss: 'isto / quanto / dinheiro',
    blank: '这个___钱',
    blankAnswer: '多少',
    note: '多少钱 e o bloco de preco, sempre vem ao fim da pergunta.',
  },
  {
    id: 'chunk-quero-isto',
    unitId: 'numbers',
    hanzi: '我要这个',
    pinyin: 'wǒ yào zhège',
    portuguese: 'eu quero este',
    gloss: 'eu / querer / este',
    blank: '我___这个',
    blankAnswer: '要',
    note: '要 (yào) funciona como pedido firme, comum em lojas e restaurantes.',
  },
  {
    id: 'chunk-cafe',
    unitId: 'numbers',
    hanzi: '我想喝咖啡',
    pinyin: 'wǒ xiǎng hē kāfēi',
    portuguese: 'eu quero (gostaria de) tomar cafe',
    gloss: 'eu / desejar / beber / cafe',
    blank: '我___喝咖啡',
    blankAnswer: '想',
    note: '想 + verbo expressa desejo educado. 喝 + bebida e o bloco classico.',
  },
  {
    id: 'chunk-vou-parque',
    unitId: 'daily',
    hanzi: '我去公园',
    pinyin: 'wǒ qù gōngyuán',
    portuguese: 'eu vou ao parque',
    gloss: 'eu / ir / parque',
    blank: '我___公园',
    blankAnswer: '去',
    note: '去 + lugar, sem preposicao no meio. Esse bloco vale para qualquer destino.',
  },
  {
    id: 'chunk-tempo',
    unitId: 'daily',
    hanzi: '今天天气好',
    pinyin: 'jīntiān tiānqì hǎo',
    portuguese: 'hoje o tempo esta bom',
    gloss: 'hoje / tempo / bom',
    blank: '今天___好',
    blankAnswer: '天气',
    note: '天气 e a unidade pronta para descrever o clima. 好 fecha o bloco.',
  },
  {
    id: 'chunk-gosto-comer',
    unitId: 'daily',
    hanzi: '我喜欢吃面',
    pinyin: 'wǒ xǐhuan chī miàn',
    portuguese: 'eu gosto de comer macarrao',
    gloss: 'eu / gostar / comer / macarrao',
    blank: '我___吃面',
    blankAnswer: '喜欢',
    note: '喜欢 + verbo + objeto e o bloco padrao para falar do que voce gosta de fazer.',
  },
  {
    id: 'chunk-que-horas',
    unitId: 'daily',
    hanzi: '现在几点',
    pinyin: 'xiànzài jǐ diǎn',
    portuguese: 'que horas sao agora?',
    gloss: 'agora / quantas / horas',
    blank: '现在___点',
    blankAnswer: '几',
    note: '几点 e o bloco fixo para perguntar horas. 现在 marca o agora.',
  },
  {
    id: 'chunk-banheiro',
    unitId: 'survival',
    hanzi: '请问厕所在哪里',
    pinyin: 'qǐngwèn cèsuǒ zài nǎli',
    portuguese: 'com licenca, onde fica o banheiro?',
    gloss: 'com licenca / banheiro / estar / onde',
    blank: '请问厕所___',
    blankAnswer: '在哪里',
    note: '在哪里 e o bloco movel: troque 厕所 por qualquer lugar que voce quer encontrar.',
  },
  {
    id: 'chunk-descansar',
    unitId: 'daily',
    hanzi: '我想休息',
    pinyin: 'wǒ xiǎng xiūxi',
    portuguese: 'quero descansar',
    gloss: 'eu / querer / descansar',
    blank: '我想___',
    blankAnswer: '休息',
    note: '想 + verbo deixa a frase util para desejos simples sem soar seco demais.',
  },
  {
    id: 'chunk-quem-e-ele',
    unitId: 'people',
    hanzi: '他是谁',
    pinyin: 'tā shì shéi',
    portuguese: 'quem e ele?',
    gloss: 'ele / ser / quem',
    blank: '他是___',
    blankAnswer: '谁',
    note: '谁 substitui a pessoa desconhecida e fecha perguntas sobre identidade.',
  },
  {
    id: 'chunk-sou-estudante',
    unitId: 'people',
    hanzi: '我是学生',
    pinyin: 'wǒ shì xuésheng',
    portuguese: 'eu sou estudante',
    gloss: 'eu / ser / estudante',
    blank: '我是___',
    blankAnswer: '学生',
    note: 'Sou + papel social: troque 学生 por 老师 para mudar a frase.',
  },
  {
    id: 'chunk-falo-chines',
    unitId: 'school',
    hanzi: '我会说中文',
    pinyin: 'wǒ huì shuō Zhōngwén',
    portuguese: 'eu sei falar chines',
    gloss: 'eu / habilidade / falar / chines',
    blank: '我会___中文',
    blankAnswer: '说',
    note: '会 + verbo marca habilidade. Aqui, a habilidade e falar.',
  },
  {
    id: 'chunk-meu-livro',
    unitId: 'school',
    hanzi: '这是我的书',
    pinyin: 'zhè shì wǒ de shū',
    portuguese: 'este e meu livro',
    gloss: 'isto / ser / meu / livro',
    blank: '这是我的___',
    blankAnswer: '书',
    note: '这是 apresenta objetos. O final troca pelo objeto que voce quer mostrar.',
  },
  {
    id: 'chunk-vou-escola',
    unitId: 'city',
    hanzi: '我去学校',
    pinyin: 'wǒ qù xuéxiào',
    portuguese: 'eu vou para a escola',
    gloss: 'eu / ir / escola',
    blank: '我___学校',
    blankAnswer: '去',
    note: '去 + destino e uma das estruturas mais produtivas do HSK1.',
  },
  {
    id: 'chunk-taxi',
    unitId: 'city',
    hanzi: '我坐出租车',
    pinyin: 'wǒ zuò chūzūchē',
    portuguese: 'eu vou de taxi',
    gloss: 'eu / pegar / taxi',
    blank: '我___出租车',
    blankAnswer: '坐',
    note: '坐 tambem aparece com trem, aviao e onibus: sentar/pegar transporte.',
  },
  {
    id: 'chunk-comprar-fruta',
    unitId: 'city',
    hanzi: '我要买水果',
    pinyin: 'wǒ yào mǎi shuǐguǒ',
    portuguese: 'eu quero comprar frutas',
    gloss: 'eu / querer / comprar / fruta',
    blank: '我要___水果',
    blankAnswer: '买',
    note: '要 + 买 cria pedido direto para comprar algo.',
  },
  {
    id: 'chunk-hoje-segunda',
    unitId: 'sky',
    hanzi: '今天星期一',
    pinyin: 'jīntiān xīngqī yī',
    portuguese: 'hoje e segunda-feira',
    gloss: 'hoje / semana / um',
    blank: '今天___一',
    blankAnswer: '星期',
    note: '星期 + numero forma os dias da semana.',
  },
  {
    id: 'chunk-um-pouco-chines',
    unitId: 'sky',
    hanzi: '我会说一点中文',
    pinyin: 'wǒ huì shuō yìdiǎn Zhōngwén',
    portuguese: 'eu sei falar um pouco de chines',
    gloss: 'eu / saber / falar / um pouco / chines',
    blank: '我会说___中文',
    blankAnswer: '一点',
    note: '一点 reduz a pressao da frase: um pouco, nao perfeitamente.',
  },
  {
    id: 'chunk-qual-nome',
    unitId: 'hsk1-gate',
    hanzi: '你叫什么名字',
    pinyin: 'nǐ jiào shénme míngzi',
    portuguese: 'qual e o seu nome?',
    gloss: 'voce / chamar / que / nome',
    blank: '你叫什么___',
    blankAnswer: '名字',
    note: '叫什么名字 e pergunta inteira de checkpoint HSK1.',
  },
  {
    id: 'chunk-onde-mora',
    unitId: 'hsk1-gate',
    hanzi: '你住在哪儿',
    pinyin: 'nǐ zhù zài nǎr',
    portuguese: 'onde voce mora?',
    gloss: 'voce / morar / em / onde',
    blank: '你住在___',
    blankAnswer: '哪儿',
    note: '哪儿 e uma forma curta e comum de perguntar onde.',
  },
]
