export type Phrase = {
  id: string
  hanzi: string
  pinyin: string
  portuguese: string
  literal: string
  note: string
  tonePattern: string
}

export type Lesson = {
  id: string
  unitId: string
  title: string
  focus: string
  xp: number
  minutes: number
  phrases: Phrase[]
}

export type Unit = {
  id: string
  title: string
  level: string
  accent: 'red' | 'jade' | 'gold' | 'ink'
  summary: string
  lessonIds: string[]
}

export type ClipSeed = {
  id: string
  title: string
  source: string
  level: string
  theme: string
  url: string
  kind: 'article' | 'video' | 'song'
}

export type StudyMoment = {
  id: string
  title: string
  source: string
  type: 'meme' | 'song' | 'anthem' | 'history'
  level: string
  phrase: string
  pinyin: string
  meaning: string
  note: string
  searchUrl: string
}

export type WritingCharacter = {
  id: string
  character: string
  pinyin: string
  meaning: string
  strokes: number
  radical: string
  words: string[]
  strokeOrder: string[]
}

export type Chunk = {
  id: string
  unitId?: Unit['id']
  hanzi: string
  pinyin: string
  portuguese: string
  gloss: string
  blank: string
  blankAnswer: string
  note: string
}

export const units: Unit[] = [
  {
    id: 'tones',
    title: 'Nadando na lagoa',
    level: 'Fase 1',
    accent: 'red',
    summary: 'O carpa testa a agua: som, ritmo, tons e primeiras silabas.',
    lessonIds: ['tones-hello', 'tones-four', 'tones-initials', 'tones-finals-family'],
  },
  {
    id: 'survival',
    title: 'Subindo o rio',
    level: 'Fase 2',
    accent: 'jade',
    summary: 'Cumprimentos, agradecimentos e respostas curtas para nao se perder na correnteza.',
    lessonIds: ['survival-greetings', 'survival-politeness', 'survival-questions', 'survival-places'],
  },
  {
    id: 'numbers',
    title: 'Cachoeira do Dragao',
    level: 'Fase 3',
    accent: 'gold',
    summary: 'Contar, perguntar preco e pedir coisas para nao parar antes da cachoeira.',
    lessonIds: ['numbers-basic', 'numbers-money', 'numbers-order', 'numbers-time'],
  },
  {
    id: 'daily',
    title: 'Saltando o Portao',
    level: 'Fase 4',
    accent: 'ink',
    summary: 'Familia, tempo, comida e rotinas: o ultimo salto antes de virar dragao.',
    lessonIds: ['daily-family', 'daily-food', 'daily-time', 'daily-feelings'],
  },
  {
    id: 'people',
    title: 'Ponte dos Pronomes',
    level: 'Fase 5',
    accent: 'red',
    summary: 'Eu, voce, ele, ela, nos e perguntas sobre pessoas.',
    lessonIds: ['people-pronouns', 'people-family', 'people-roles'],
  },
  {
    id: 'school',
    title: 'Casa do Estudo',
    level: 'Fase 6',
    accent: 'jade',
    summary: 'Chines, livro, professor, estudante e a rotina de aprender.',
    lessonIds: ['school-language', 'school-classroom', 'school-actions'],
  },
  {
    id: 'city',
    title: 'Mercado de Jade',
    level: 'Fase 7',
    accent: 'gold',
    summary: 'Ir, vir, comprar, lojas, transporte e lugares da cidade.',
    lessonIds: ['city-going', 'city-transport', 'city-shopping'],
  },
  {
    id: 'sky',
    title: 'Ceu das Horas',
    level: 'Fase 8',
    accent: 'ink',
    summary: 'Dias da semana, clima, agora, gostar e saber fazer.',
    lessonIds: ['sky-week', 'sky-weather', 'sky-ability'],
  },
  {
    id: 'hsk1-gate',
    title: 'Portao HSK1',
    level: 'Fase 9',
    accent: 'red',
    summary: 'Mini-dialogos de prova: nome, nacionalidade, idade e moradia.',
    lessonIds: ['gate-name', 'gate-origin-age', 'gate-home-check'],
  },
]

export const lessons: Lesson[] = [
  {
    id: 'tones-hello',
    unitId: 'tones',
    title: 'Ola sem tropeçar nos tons',
    focus: 'Tons 3-3, saudacao basica',
    xp: 15,
    minutes: 5,
    phrases: [
      {
        id: 'ni-hao',
        hanzi: '你好',
        pinyin: 'nǐ hǎo',
        portuguese: 'ola',
        literal: 'voce bom',
        note: 'Na fala natural, o primeiro terceiro tom sobe para soar mais leve.',
        tonePattern: '3-3',
      },
      {
        id: 'wo-hen-hao',
        hanzi: '我很好',
        pinyin: 'wǒ hěn hǎo',
        portuguese: 'eu estou bem',
        literal: 'eu muito bom',
        note: 'hen suaviza a frase; nem sempre significa "muito" nesse contexto.',
        tonePattern: '3-3-3',
      },
    ],
  },
  {
    id: 'tones-four',
    unitId: 'tones',
    title: 'Quatro tons, uma silaba',
    focus: 'ma nos tons 1, 2, 3 e 4',
    xp: 20,
    minutes: 6,
    phrases: [
      {
        id: 'ma-tones',
        hanzi: '妈 麻 马 骂',
        pinyin: 'mā má mǎ mà',
        portuguese: 'mae, canhamo, cavalo, xingar',
        literal: 'quatro tons com ma',
        note: 'A mesma silaba muda de significado quando o tom muda.',
        tonePattern: '1-2-3-4',
      },
      {
        id: 'shi-tones',
        hanzi: '是 十 事',
        pinyin: 'shì shí shì',
        portuguese: 'ser, dez, assunto',
        literal: 'sons parecidos, tons diferentes',
        note: 'Ouvir pares minimos ajuda a separar significado por tom.',
        tonePattern: '4-2-4',
      },
    ],
  },
  {
    id: 'tones-initials',
    unitId: 'tones',
    title: 'Iniciais que confundem',
    focus: 'zh, ch, sh, r',
    xp: 20,
    minutes: 7,
    phrases: [
      {
        id: 'zhong-guo',
        hanzi: '中国',
        pinyin: 'Zhōngguó',
        portuguese: 'China',
        literal: 'pais do meio',
        note: 'zh tem a lingua enrolada para tras, diferente de z.',
        tonePattern: '1-2',
      },
      {
        id: 'ren',
        hanzi: '人',
        pinyin: 'rén',
        portuguese: 'pessoa',
        literal: 'pessoa',
        note: 'O r em mandarim fica entre r, zh e um som mais retroflexo.',
        tonePattern: '2',
      },
    ],
  },
  {
    id: 'tones-finals-family',
    unitId: 'tones',
    title: 'Finais com voz clara',
    focus: 'a, ao, ang e tom neutro',
    xp: 18,
    minutes: 6,
    phrases: [
      {
        id: 'ba-ba',
        hanzi: '爸爸',
        pinyin: 'bàba',
        portuguese: 'pai',
        literal: 'pai',
        note: 'A segunda silaba fica leve; treine sem transformar em um novo tom forte.',
        tonePattern: '4-0',
      },
      {
        id: 'ma-ma',
        hanzi: '妈妈',
        pinyin: 'māma',
        portuguese: 'mae',
        literal: 'mae',
        note: 'Repita devagar e depois natural, deixando o segundo ma mais curto.',
        tonePattern: '1-0',
      },
    ],
  },
  {
    id: 'survival-greetings',
    unitId: 'survival',
    title: 'Cumprimentos reais',
    focus: 'ola, ate logo, nome',
    xp: 18,
    minutes: 6,
    phrases: [
      {
        id: 'zao-shang-hao',
        hanzi: '早上好',
        pinyin: 'zǎoshang hǎo',
        portuguese: 'bom dia',
        literal: 'manha boa',
        note: 'Usado pela manha; ni hao ainda funciona em muitas situacoes.',
        tonePattern: '3-0-3',
      },
      {
        id: 'zai-jian',
        hanzi: '再见',
        pinyin: 'zàijiàn',
        portuguese: 'tchau',
        literal: 'ver de novo',
        note: 'Formal o suficiente para quase qualquer contexto.',
        tonePattern: '4-4',
      },
    ],
  },
  {
    id: 'survival-politeness',
    unitId: 'survival',
    title: 'Educacao rapida',
    focus: 'obrigado, desculpa, sem problema',
    xp: 18,
    minutes: 6,
    phrases: [
      {
        id: 'xie-xie',
        hanzi: '谢谢',
        pinyin: 'xièxie',
        portuguese: 'obrigado',
        literal: 'agradecer',
        note: 'A segunda silaba costuma ficar mais leve.',
        tonePattern: '4-0',
      },
      {
        id: 'mei-guan-xi',
        hanzi: '没关系',
        pinyin: 'méi guānxi',
        portuguese: 'sem problema',
        literal: 'nao tem relacao',
        note: 'Resposta natural para desculpas ou pequenos erros.',
        tonePattern: '2-1-0',
      },
    ],
  },
  {
    id: 'survival-questions',
    unitId: 'survival',
    title: 'Perguntas pequenas',
    focus: 'particula ma e perguntas simples',
    xp: 20,
    minutes: 7,
    phrases: [
      {
        id: 'ni-hao-ma',
        hanzi: '你好吗？',
        pinyin: 'nǐ hǎo ma?',
        portuguese: 'voce esta bem?',
        literal: 'voce bom pergunta',
        note: 'ma transforma uma frase em pergunta sim/nao.',
        tonePattern: '3-3-0',
      },
      {
        id: 'shen-me',
        hanzi: '什么？',
        pinyin: 'shénme?',
        portuguese: 'o que?',
        literal: 'que coisa',
        note: 'Uma das palavras de pergunta mais frequentes.',
        tonePattern: '2-0',
      },
    ],
  },
  {
    id: 'survival-places',
    unitId: 'survival',
    title: 'Nao se perder',
    focus: 'perguntar com educacao e achar lugares',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'qing-wen',
        hanzi: '请问',
        pinyin: 'qǐngwèn',
        portuguese: 'com licenca',
        literal: 'por favor perguntar',
        note: 'Use antes de perguntas para soar educado com desconhecidos.',
        tonePattern: '3-4',
      },
      {
        id: 'ce-suo-zai-na-li',
        hanzi: '厕所在哪里？',
        pinyin: 'cèsuǒ zài nǎli?',
        portuguese: 'onde fica o banheiro?',
        literal: 'banheiro estar onde',
        note: '在哪里 e um bloco pronto para perguntar onde algo fica.',
        tonePattern: '4-3-4-3-0',
      },
    ],
  },
  {
    id: 'numbers-basic',
    unitId: 'numbers',
    title: 'Numeros 1 a 10',
    focus: 'contagem e reconhecimento auditivo',
    xp: 16,
    minutes: 5,
    phrases: [
      {
        id: 'yi-er-san',
        hanzi: '一 二 三',
        pinyin: 'yī, èr, sān',
        portuguese: 'um, dois, tres',
        literal: '1 2 3',
        note: 'yi muda de tom em combinacoes, mas primeiro memorize o som base.',
        tonePattern: '1-4-1',
      },
      {
        id: 'shi',
        hanzi: '十',
        pinyin: 'shí',
        portuguese: 'dez',
        literal: '10',
        note: 'O segundo tom sobe, como uma pergunta curta.',
        tonePattern: '2',
      },
    ],
  },
  {
    id: 'numbers-money',
    unitId: 'numbers',
    title: 'Quanto custa?',
    focus: 'preco e demonstrativos',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'duo-shao-qian',
        hanzi: '多少钱？',
        pinyin: 'duōshao qián?',
        portuguese: 'quanto custa?',
        literal: 'quanto dinheiro',
        note: 'Frase pronta para lojas, mercados e taxis.',
        tonePattern: '1-0-2',
      },
      {
        id: 'zhe-ge',
        hanzi: '这个',
        pinyin: 'zhège',
        portuguese: 'este',
        literal: 'este item',
        note: 'Muito usado apontando para algo que voce quer.',
        tonePattern: '4-0',
      },
    ],
  },
  {
    id: 'numbers-order',
    unitId: 'numbers',
    title: 'Pedir comida',
    focus: 'quero, uma unidade, agua',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'wo-yao',
        hanzi: '我要',
        pinyin: 'wǒ yào',
        portuguese: 'eu quero',
        literal: 'eu querer',
        note: 'Funciona para pedidos simples, mas use com educacao.',
        tonePattern: '3-4',
      },
      {
        id: 'yi-bei-shui',
        hanzi: '一杯水',
        pinyin: 'yì bēi shuǐ',
        portuguese: 'um copo de agua',
        literal: 'um copo agua',
        note: 'bei e o classificador para copos e bebidas.',
        tonePattern: '4-1-3',
      },
    ],
  },
  {
    id: 'numbers-time',
    unitId: 'numbers',
    title: 'Horario sem travar',
    focus: 'horas, hoje e amanha',
    xp: 20,
    minutes: 6,
    phrases: [
      {
        id: 'san-dian',
        hanzi: '三点',
        pinyin: 'sān diǎn',
        portuguese: 'tres horas',
        literal: 'tres ponto',
        note: '点 marca horas cheias: 三点 e tres horas.',
        tonePattern: '1-3',
      },
      {
        id: 'ming-tian-shi-dian',
        hanzi: '明天十点',
        pinyin: 'míngtiān shí diǎn',
        portuguese: 'amanha as dez',
        literal: 'amanha dez horas',
        note: 'Coloque o tempo antes do horario para combinar planos simples.',
        tonePattern: '2-1-2-3',
      },
    ],
  },
  {
    id: 'daily-family',
    unitId: 'daily',
    title: 'Familia',
    focus: 'pessoas proximas',
    xp: 18,
    minutes: 6,
    phrases: [
      {
        id: 'wo-de-jia',
        hanzi: '我的家',
        pinyin: 'wǒ de jiā',
        portuguese: 'minha familia / minha casa',
        literal: 'eu possessivo casa',
        note: 'jia pode ser casa ou familia dependendo do contexto.',
        tonePattern: '3-0-1',
      },
      {
        id: 'peng-you',
        hanzi: '朋友',
        pinyin: 'péngyou',
        portuguese: 'amigo',
        literal: 'amigo',
        note: 'A segunda silaba e neutra na fala comum.',
        tonePattern: '2-0',
      },
    ],
  },
  {
    id: 'daily-food',
    unitId: 'daily',
    title: 'Comida do dia a dia',
    focus: 'comer, beber, arroz',
    xp: 20,
    minutes: 7,
    phrases: [
      {
        id: 'chi-fan',
        hanzi: '吃饭',
        pinyin: 'chī fàn',
        portuguese: 'comer / fazer refeicao',
        literal: 'comer arroz',
        note: 'Chifan virou uma expressao geral para fazer uma refeicao.',
        tonePattern: '1-4',
      },
      {
        id: 'he-shui',
        hanzi: '喝水',
        pinyin: 'hē shuǐ',
        portuguese: 'beber agua',
        literal: 'beber agua',
        note: 'h em he e aspirado, com ar saindo claro.',
        tonePattern: '1-3',
      },
    ],
  },
  {
    id: 'daily-time',
    unitId: 'daily',
    title: 'Hoje, agora, amanha',
    focus: 'tempo basico',
    xp: 20,
    minutes: 7,
    phrases: [
      {
        id: 'jin-tian',
        hanzi: '今天',
        pinyin: 'jīntiān',
        portuguese: 'hoje',
        literal: 'este dia',
        note: 'j exige a lingua mais alta, perto do som de ji.',
        tonePattern: '1-1',
      },
      {
        id: 'ming-tian',
        hanzi: '明天',
        pinyin: 'míngtiān',
        portuguese: 'amanha',
        literal: 'dia claro',
        note: 'Muito util para combinar horarios simples.',
        tonePattern: '2-1',
      },
    ],
  },
  {
    id: 'daily-feelings',
    unitId: 'daily',
    title: 'Corpo e energia',
    focus: 'cansaco, descanso e ritmo do dia',
    xp: 20,
    minutes: 7,
    phrases: [
      {
        id: 'wo-lei-le',
        hanzi: '我累了',
        pinyin: 'wǒ lèi le',
        portuguese: 'estou cansado',
        literal: 'eu cansado mudanca',
        note: '了 marca que o estado mudou: agora estou cansado.',
        tonePattern: '3-4-0',
      },
      {
        id: 'wo-xiang-xiu-xi',
        hanzi: '我想休息',
        pinyin: 'wǒ xiǎng xiūxi',
        portuguese: 'quero descansar',
        literal: 'eu querer descansar',
        note: '想 suaviza o pedido e funciona bem antes de verbos.',
        tonePattern: '3-3-1-0',
      },
    ],
  },
  {
    id: 'people-pronouns',
    unitId: 'people',
    title: 'Quem esta falando?',
    focus: 'eu, voce, ele, ela, quem',
    xp: 20,
    minutes: 6,
    phrases: [
      {
        id: 'ta-shi-shei',
        hanzi: '他是谁？',
        pinyin: 'tā shì shéi?',
        portuguese: 'quem e ele?',
        literal: 'ele ser quem',
        note: '谁 pergunta sobre pessoa. Troque 他 por 她 para falar dela.',
        tonePattern: '1-4-2',
      },
      {
        id: 'ta-shi-wo-pengyou',
        hanzi: '她是我朋友',
        pinyin: 'tā shì wǒ péngyou',
        portuguese: 'ela e minha amiga',
        literal: 'ela ser eu amiga',
        note: 'Em fala simples, 我朋友 funciona como "minha amiga" sem 的.',
        tonePattern: '1-4-3-2-0',
      },
    ],
  },
  {
    id: 'people-family',
    unitId: 'people',
    title: 'Familia perto de voce',
    focus: 'familia, pai, mae, todos',
    xp: 20,
    minutes: 6,
    phrases: [
      {
        id: 'wo-ai-wo-de-jia',
        hanzi: '我爱我的家',
        pinyin: 'wǒ ài wǒ de jiā',
        portuguese: 'eu amo minha familia',
        literal: 'eu amar minha casa/familia',
        note: '爱 e direto; 家 pode ser casa ou familia pelo contexto.',
        tonePattern: '3-4-3-0-1',
      },
      {
        id: 'ba-ma-dou-hao',
        hanzi: '爸爸妈妈都好',
        pinyin: 'bàba māma dōu hǎo',
        portuguese: 'papai e mamae estao bem',
        literal: 'pai mae todos bem',
        note: '都 marca que a ideia vale para todos no grupo.',
        tonePattern: '4-0-1-0-1-3',
      },
    ],
  },
  {
    id: 'people-roles',
    unitId: 'people',
    title: 'Professor e estudante',
    focus: 'profissao escolar basica',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'ta-shi-laoshi',
        hanzi: '他是老师',
        pinyin: 'tā shì lǎoshī',
        portuguese: 'ele e professor',
        literal: 'ele ser professor',
        note: '老师 e uma das primeiras palavras sociais do HSK1.',
        tonePattern: '1-4-3-1',
      },
      {
        id: 'wo-shi-xuesheng',
        hanzi: '我是学生',
        pinyin: 'wǒ shì xuésheng',
        portuguese: 'eu sou estudante',
        literal: 'eu ser estudante',
        note: '学生 tem segunda silaba leve na fala natural.',
        tonePattern: '3-4-2-0',
      },
    ],
  },
  {
    id: 'school-language',
    unitId: 'school',
    title: 'Abrindo o livro de chines',
    focus: 'estudar, chines, falar',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'wo-xuexi-zhongwen',
        hanzi: '我学习中文',
        pinyin: 'wǒ xuéxí Zhōngwén',
        portuguese: 'eu estudo chines',
        literal: 'eu estudar lingua chinesa',
        note: '学习 e o verbo base para estudar; 中文 e a lingua chinesa.',
        tonePattern: '3-2-2-1-2',
      },
      {
        id: 'ni-hui-shuo-zhongwen-ma',
        hanzi: '你会说中文吗？',
        pinyin: 'nǐ huì shuō Zhōngwén ma?',
        portuguese: 'voce sabe falar chines?',
        literal: 'voce saber falar chines pergunta',
        note: '会 fala de habilidade: saber/conseguir fazer algo.',
        tonePattern: '3-4-1-1-2-0',
      },
    ],
  },
  {
    id: 'school-classroom',
    unitId: 'school',
    title: 'Coisas da sala',
    focus: 'livro, mesa, computador',
    xp: 20,
    minutes: 6,
    phrases: [
      {
        id: 'zhe-shi-wo-de-shu',
        hanzi: '这是我的书',
        pinyin: 'zhè shì wǒ de shū',
        portuguese: 'este e meu livro',
        literal: 'isto ser meu livro',
        note: '这是... apresenta objetos de forma simples.',
        tonePattern: '4-4-3-0-1',
      },
      {
        id: 'diannao-zai-zhuozi-shang',
        hanzi: '电脑在桌子上',
        pinyin: 'diànnǎo zài zhuōzi shàng',
        portuguese: 'o computador esta em cima da mesa',
        literal: 'computador estar mesa em cima',
        note: '在 + lugar localiza coisas; 上 marca "em cima".',
        tonePattern: '4-3-4-1-0-4',
      },
    ],
  },
  {
    id: 'school-actions',
    unitId: 'school',
    title: 'Ler, escrever, escutar',
    focus: 'acoes de estudo',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'wo-kan-shu',
        hanzi: '我看书',
        pinyin: 'wǒ kàn shū',
        portuguese: 'eu leio livro',
        literal: 'eu olhar livro',
        note: '看 cobre ver/olhar/ler dependendo do objeto.',
        tonePattern: '3-4-1',
      },
      {
        id: 'qing-xie-hanzi',
        hanzi: '请写汉字',
        pinyin: 'qǐng xiě hànzì',
        portuguese: 'por favor escreva hanzi',
        literal: 'por favor escrever caracteres chineses',
        note: '请 deixa o comando educado; 写 e escrever.',
        tonePattern: '3-3-4-4',
      },
    ],
  },
  {
    id: 'city-going',
    unitId: 'city',
    title: 'Ir e vir pela cidade',
    focus: 'ir, vir, escola, China',
    xp: 20,
    minutes: 6,
    phrases: [
      {
        id: 'wo-qu-xuexiao',
        hanzi: '我去学校',
        pinyin: 'wǒ qù xuéxiào',
        portuguese: 'eu vou para a escola',
        literal: 'eu ir escola',
        note: '去 + lugar: estrutura limpa para destino.',
        tonePattern: '3-4-2-4',
      },
      {
        id: 'ta-lai-zhongguo',
        hanzi: '他来中国',
        pinyin: 'tā lái Zhōngguó',
        portuguese: 'ele vem para a China',
        literal: 'ele vir China',
        note: '来 aponta movimento vindo para perto do falante/contexto.',
        tonePattern: '1-2-1-2',
      },
    ],
  },
  {
    id: 'city-transport',
    unitId: 'city',
    title: 'Taxi, trem e caminho',
    focus: 'transporte e lugar',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'wo-zuo-chuzuche',
        hanzi: '我坐出租车',
        pinyin: 'wǒ zuò chūzūchē',
        portuguese: 'eu vou de taxi',
        literal: 'eu sentar taxi',
        note: '坐 e usado para transporte: sentar/pegar um veiculo.',
        tonePattern: '3-4-1-1-1',
      },
      {
        id: 'huochezhan-zai-nali',
        hanzi: '火车站在哪里？',
        pinyin: 'huǒchēzhàn zài nǎli?',
        portuguese: 'onde fica a estacao de trem?',
        literal: 'estacao de trem estar onde',
        note: '在哪里 reaparece: troque o lugar e a pergunta continua pronta.',
        tonePattern: '3-1-4-4-3-0',
      },
    ],
  },
  {
    id: 'city-shopping',
    unitId: 'city',
    title: 'Comprar no mercado',
    focus: 'loja, ter, comprar, fruta',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'shangdian-you-shui',
        hanzi: '商店有水',
        pinyin: 'shāngdiàn yǒu shuǐ',
        portuguese: 'a loja tem agua',
        literal: 'loja ter agua',
        note: '有 marca existencia/posse: tem, ha.',
        tonePattern: '1-4-3-3',
      },
      {
        id: 'wo-yao-mai-shuiguo',
        hanzi: '我要买水果',
        pinyin: 'wǒ yào mǎi shuǐguǒ',
        portuguese: 'eu quero comprar frutas',
        literal: 'eu querer comprar fruta',
        note: '买 e comprar; 水果 junta agua+fruto, mas significa fruta.',
        tonePattern: '3-4-3-3-3',
      },
    ],
  },
  {
    id: 'sky-week',
    unitId: 'sky',
    title: 'Semana e agora',
    focus: 'semana, hoje, agora',
    xp: 20,
    minutes: 6,
    phrases: [
      {
        id: 'jintian-xingqi-yi',
        hanzi: '今天星期一',
        pinyin: 'jīntiān xīngqī yī',
        portuguese: 'hoje e segunda-feira',
        literal: 'hoje semana um',
        note: '星期 + numero forma os dias da semana.',
        tonePattern: '1-1-1-1-1',
      },
      {
        id: 'xianzai-ba-dian',
        hanzi: '现在八点',
        pinyin: 'xiànzài bā diǎn',
        portuguese: 'agora sao oito horas',
        literal: 'agora oito horas',
        note: '现在 coloca a frase no presente imediato.',
        tonePattern: '4-4-1-3',
      },
    ],
  },
  {
    id: 'sky-weather',
    unitId: 'sky',
    title: 'Clima simples',
    focus: 'tempo bom, chuva, quente, frio',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'tianqi-hen-hao',
        hanzi: '天气很好',
        pinyin: 'tiānqì hěn hǎo',
        portuguese: 'o tempo esta bom',
        literal: 'tempo muito bom',
        note: '天气 e clima/tempo meteorologico. 很 suaviza adjetivos.',
        tonePattern: '1-4-3-3',
      },
      {
        id: 'xianzai-xia-yu',
        hanzi: '现在下雨',
        pinyin: 'xiànzài xià yǔ',
        portuguese: 'agora esta chovendo',
        literal: 'agora cair chuva',
        note: '下雨 e o bloco comum para chover.',
        tonePattern: '4-4-4-3',
      },
    ],
  },
  {
    id: 'sky-ability',
    unitId: 'sky',
    title: 'Gosto e habilidade',
    focus: 'gostar, saber fazer, um pouco',
    xp: 22,
    minutes: 7,
    phrases: [
      {
        id: 'wo-hui-shuo-yidian-zhongwen',
        hanzi: '我会说一点中文',
        pinyin: 'wǒ huì shuō yìdiǎn Zhōngwén',
        portuguese: 'eu sei falar um pouco de chines',
        literal: 'eu saber falar um pouco chines',
        note: '一点 deixa a frase humilde: um pouco.',
        tonePattern: '3-4-1-4-3-1-2',
      },
      {
        id: 'wo-xihuan-he-cha',
        hanzi: '我喜欢喝茶',
        pinyin: 'wǒ xǐhuan hē chá',
        portuguese: 'eu gosto de beber cha',
        literal: 'eu gostar beber cha',
        note: '喜欢 + verbo/objeto expressa preferencia.',
        tonePattern: '3-3-0-1-2',
      },
    ],
  },
  {
    id: 'gate-name',
    unitId: 'hsk1-gate',
    title: 'Checkpoint: nome',
    focus: 'dialogo de apresentacao',
    xp: 24,
    minutes: 7,
    phrases: [
      {
        id: 'ni-jiao-shenme-mingzi',
        hanzi: '你叫什么名字？',
        pinyin: 'nǐ jiào shénme míngzi?',
        portuguese: 'qual e o seu nome?',
        literal: 'voce chamar que nome',
        note: '叫什么名字 e pergunta padrao de apresentacao.',
        tonePattern: '3-4-2-0-2-0',
      },
      {
        id: 'wo-jiao-kauan',
        hanzi: '我叫卡蓝',
        pinyin: 'wǒ jiào Kǎlán',
        portuguese: 'me chamo Kauan',
        literal: 'eu chamar Kauan',
        note: 'Troque 卡蓝 pelo seu nome chines ou transliterado.',
        tonePattern: '3-4-3-2',
      },
    ],
  },
  {
    id: 'gate-origin-age',
    unitId: 'hsk1-gate',
    title: 'Checkpoint: origem e idade',
    focus: 'pais, idade, anos',
    xp: 24,
    minutes: 8,
    phrases: [
      {
        id: 'ni-shi-na-guo-ren',
        hanzi: '你是哪国人？',
        pinyin: 'nǐ shì nǎ guó rén?',
        portuguese: 'de que pais voce e?',
        literal: 'voce ser qual pais pessoa',
        note: '哪国人 pergunta nacionalidade de forma compacta.',
        tonePattern: '3-4-3-2-2',
      },
      {
        id: 'wo-ershi-sui',
        hanzi: '我二十岁',
        pinyin: 'wǒ èrshí suì',
        portuguese: 'eu tenho vinte anos',
        literal: 'eu vinte anos',
        note: '岁 marca idade; nao precisa de verbo "ter".',
        tonePattern: '3-4-2-4',
      },
    ],
  },
  {
    id: 'gate-home-check',
    unitId: 'hsk1-gate',
    title: 'Checkpoint: morar',
    focus: 'morar, cidade, lugar',
    xp: 24,
    minutes: 8,
    phrases: [
      {
        id: 'ni-zhu-zai-nar',
        hanzi: '你住在哪儿？',
        pinyin: 'nǐ zhù zài nǎr?',
        portuguese: 'onde voce mora?',
        literal: 'voce morar em onde',
        note: '住在 + lugar monta a frase de moradia.',
        tonePattern: '3-4-4-3',
      },
      {
        id: 'wo-zhu-zai-beijing',
        hanzi: '我住在北京',
        pinyin: 'wǒ zhù zài Běijīng',
        portuguese: 'eu moro em Pequim',
        literal: 'eu morar em Pequim',
        note: 'Troque 北京 pela cidade que voce quer dizer.',
        tonePattern: '3-4-4-3-1',
      },
    ],
  },
]

export const clipSeeds: ClipSeed[] = [
  {
    id: 'pinyin-chart',
    title: 'Tabela de pinyin com audio',
    source: 'Yoyo Chinese',
    level: 'Fundacao',
    theme: 'pinyin',
    kind: 'article',
    url: 'https://yoyochinese.com/chinese-learning-tools/Mandarin-Chinese-pronunciation-lesson/pinyin-chart-table',
  },
  {
    id: 'digmandarin-pinyin',
    title: 'Guia completo de pinyin',
    source: 'DigMandarin',
    level: 'Fundacao',
    theme: 'tons',
    kind: 'article',
    url: 'https://www.digmandarin.com/learn-chinese-pinyin',
  },
  {
    id: 'goeast-pronunciation',
    title: 'Pronuncia e pares minimos',
    source: 'GoEast Mandarin',
    level: 'HSK 1',
    theme: 'pronuncia',
    kind: 'article',
    url: 'https://goeastmandarin.com/chinese-pronunciation/',
  },
  {
    id: 'music-lab',
    title: 'Aprender chines com musica',
    source: 'Chinese with Ping',
    level: 'Livre',
    theme: 'musica',
    kind: 'song',
    url: 'https://www.chinesewithping.com/',
  },
]

export const studyMoments: StudyMoment[] = [
  {
    id: 'super-idol',
    title: 'Super Idol',
    source: 'Meme musical',
    type: 'song',
    level: 'Livre',
    phrase: '笑容',
    pinyin: 'xiàoróng',
    meaning: 'sorriso',
    note: 'Use o meme para treinar xiao, rong e o segundo tom subindo no final.',
    searchUrl: 'https://www.youtube.com/results?search_query=Super+Idol+Chinese+lyrics+learning',
  },
  {
    id: 'john-cena-bing-chilling',
    title: 'John Cena falando mandarim',
    source: 'Meme de entrevista',
    type: 'meme',
    level: 'HSK 1',
    phrase: '冰淇淋',
    pinyin: 'bīngqílín',
    meaning: 'sorvete',
    note: 'Palavra divertida para treinar b, q e tons em sequencia.',
    searchUrl: 'https://www.youtube.com/results?search_query=John+Cena+Mandarin+bing+chilling',
  },
  {
    id: 'chinese-anthem',
    title: 'Hino chines',
    source: 'Musica civica',
    type: 'anthem',
    level: 'Interesse cultural',
    phrase: '起来',
    pinyin: 'qǐlái',
    meaning: 'levantar-se',
    note: 'Boa palavra para perceber terceiro tom seguido de segundo tom.',
    searchUrl: 'https://www.youtube.com/results?search_query=Chinese+national+anthem+lyrics+pinyin',
  },
  {
    id: 'mao-historical-song',
    title: 'Cancoes historicas de Mao Zedong',
    source: 'Contexto historico',
    type: 'history',
    level: 'Cultura',
    phrase: '东方红',
    pinyin: 'Dōngfāng hóng',
    meaning: 'o oriente e vermelho',
    note: 'Use como contexto cultural e para treinar dong, fang e hong sem depender de traducao literal.',
    searchUrl: 'https://www.youtube.com/results?search_query=The+East+is+Red+Chinese+pinyin',
  },
  {
    id: 'football-meme',
    title: 'Meme de torcida',
    source: 'Frase viral',
    type: 'meme',
    level: 'HSK 1',
    phrase: '加油',
    pinyin: 'jiāyóu',
    meaning: 'forca / vamos la',
    note: 'Perfeito para jogos, desafios e rankings entre amigos.',
    searchUrl: 'https://www.youtube.com/results?search_query=jiayou+Chinese+meme',
  },
]

export const allPhrases = lessons.flatMap((lesson) =>
  lesson.phrases.map((phrase) => ({
    ...phrase,
    lessonId: lesson.id,
    lessonTitle: lesson.title,
    unitId: lesson.unitId,
  })),
)

export const toneDrills = [
  {
    id: 'ma',
    title: 'ma em quatro tons',
    hanzi: '妈 麻 马 骂',
    pinyin: 'mā má mǎ mà',
    focus: 'Altura da voz',
  },
  {
    id: 'hao',
    title: 'terceiro tom em sequencia',
    hanzi: '你好 很好',
    pinyin: 'nǐ hǎo, hěn hǎo',
    focus: 'Mudanca do terceiro tom',
  },
  {
    id: 'shi',
    title: 'sh e tons curtos',
    hanzi: '是 十 事',
    pinyin: 'shì shí shì',
    focus: 'Retroflexo e contraste',
  },
]

export const writingCharacters: WritingCharacter[] = [
  {
    id: 'ren',
    character: '人',
    pinyin: 'rén',
    meaning: 'pessoa',
    strokes: 2,
    radical: '人',
    words: ['人', '中国人', '朋友'],
    strokeOrder: ['Traço descendente para a esquerda.', 'Traço descendente para a direita, abrindo a base.'],
  },
  {
    id: 'kou',
    character: '口',
    pinyin: 'kǒu',
    meaning: 'boca / abertura',
    strokes: 3,
    radical: '口',
    words: ['口', '人口', '门口'],
    strokeOrder: ['Vertical esquerda.', 'Canto superior e vertical direita.', 'Linha inferior fechando o quadrado.'],
  },
  {
    id: 'ni',
    character: '你',
    pinyin: 'nǐ',
    meaning: 'voce',
    strokes: 7,
    radical: '亻',
    words: ['你好', '你们', '你好吗'],
    strokeOrder: [
      'Componente pessoa: traço inclinado curto.',
      'Vertical do componente pessoa.',
      'Pequeno traço inclinado no topo direito.',
      'Gancho horizontal descendo no centro.',
      'Traço vertical com gancho.',
      'Ponto esquerdo.',
      'Ponto direito.',
    ],
  },
  {
    id: 'hao',
    character: '好',
    pinyin: 'hǎo',
    meaning: 'bom / bem',
    strokes: 6,
    radical: '女',
    words: ['你好', '很好', '好吃'],
    strokeOrder: [
      'Mulher: traço curvo para baixo.',
      'Traço inclinado cruzando.',
      'Horizontal do componente mulher.',
      'Filho: traço horizontal curto.',
      'Gancho vertical.',
      'Horizontal final atravessando o componente filho.',
    ],
  },
  {
    id: 'zhong',
    character: '中',
    pinyin: 'zhōng',
    meaning: 'meio / China',
    strokes: 4,
    radical: '丨',
    words: ['中国', '中文', '中午'],
    strokeOrder: ['Caixa externa esquerda.', 'Topo e direita da caixa.', 'Base da caixa.', 'Vertical central atravessando.'],
  },
  {
    id: 'shui',
    character: '水',
    pinyin: 'shuǐ',
    meaning: 'agua',
    strokes: 4,
    radical: '水',
    words: ['喝水', '一杯水', '水果'],
    strokeOrder: ['Vertical com gancho no centro.', 'Traço descendente esquerdo.', 'Traço curto direito.', 'Traço longo direito.'],
  },
]

export const chunks: Chunk[] = [
  {
    id: 'chunk-meu-nome',
    unitId: 'survival',
    hanzi: '我叫卡蓝',
    pinyin: 'wǒ jiào Kǎ-lán',
    portuguese: 'me chamo Kauan',
    gloss: 'eu / chamar / Kauan',
    blank: '我___卡蓝',
    blankAnswer: '叫',
    note: 'Use 叫 (jiào) para apresentar como gosta de ser chamado. Troque o final pelo seu nome.',
  },
  {
    id: 'chunk-tudo-bem',
    unitId: 'survival',
    hanzi: '你好吗',
    pinyin: 'nǐ hǎo ma',
    portuguese: 'tudo bem?',
    gloss: 'voce / bem / (pergunta)',
    blank: '你好___',
    blankAnswer: '吗',
    note: 'A particula 吗 (ma) transforma uma afirmacao em pergunta sim/nao.',
  },
  {
    id: 'chunk-obrigado',
    unitId: 'survival',
    hanzi: '谢谢你',
    pinyin: 'xièxie nǐ',
    portuguese: 'obrigado a voce',
    gloss: 'obrigado / voce',
    blank: '谢谢___',
    blankAnswer: '你',
    note: 'Bloco fixo: 谢谢 vai sempre antes do alvo do agradecimento.',
  },
  {
    id: 'chunk-quanto-custa',
    unitId: 'numbers',
    hanzi: '这个多少钱',
    pinyin: 'zhège duōshao qián',
    portuguese: 'quanto custa isto?',
    gloss: 'isto / quanto / dinheiro',
    blank: '这个___钱',
    blankAnswer: '多少',
    note: '多少钱 e o bloco de preco, sempre vem ao fim da pergunta.',
  },
  {
    id: 'chunk-quero-isto',
    unitId: 'numbers',
    hanzi: '我要这个',
    pinyin: 'wǒ yào zhège',
    portuguese: 'eu quero este',
    gloss: 'eu / querer / este',
    blank: '我___这个',
    blankAnswer: '要',
    note: '要 (yào) funciona como pedido firme, comum em lojas e restaurantes.',
  },
  {
    id: 'chunk-cafe',
    unitId: 'numbers',
    hanzi: '我想喝咖啡',
    pinyin: 'wǒ xiǎng hē kāfēi',
    portuguese: 'eu quero (gostaria de) tomar cafe',
    gloss: 'eu / desejar / beber / cafe',
    blank: '我___喝咖啡',
    blankAnswer: '想',
    note: '想 + verbo expressa desejo educado. 喝 + bebida e o bloco classico.',
  },
  {
    id: 'chunk-vou-parque',
    unitId: 'daily',
    hanzi: '我去公园',
    pinyin: 'wǒ qù gōngyuán',
    portuguese: 'eu vou ao parque',
    gloss: 'eu / ir / parque',
    blank: '我___公园',
    blankAnswer: '去',
    note: '去 + lugar, sem preposicao no meio. Esse bloco vale para qualquer destino.',
  },
  {
    id: 'chunk-tempo',
    unitId: 'daily',
    hanzi: '今天天气好',
    pinyin: 'jīntiān tiānqì hǎo',
    portuguese: 'hoje o tempo esta bom',
    gloss: 'hoje / tempo / bom',
    blank: '今天___好',
    blankAnswer: '天气',
    note: '天气 e a unidade pronta para descrever o clima. 好 fecha o bloco.',
  },
  {
    id: 'chunk-gosto-comer',
    unitId: 'daily',
    hanzi: '我喜欢吃面',
    pinyin: 'wǒ xǐhuan chī miàn',
    portuguese: 'eu gosto de comer macarrao',
    gloss: 'eu / gostar / comer / macarrao',
    blank: '我___吃面',
    blankAnswer: '喜欢',
    note: '喜欢 + verbo + objeto e o bloco padrao para falar do que voce gosta de fazer.',
  },
  {
    id: 'chunk-que-horas',
    unitId: 'daily',
    hanzi: '现在几点',
    pinyin: 'xiànzài jǐ diǎn',
    portuguese: 'que horas sao agora?',
    gloss: 'agora / quantas / horas',
    blank: '现在___点',
    blankAnswer: '几',
    note: '几点 e o bloco fixo para perguntar horas. 现在 marca o agora.',
  },
  {
    id: 'chunk-banheiro',
    unitId: 'survival',
    hanzi: '请问厕所在哪里',
    pinyin: 'qǐngwèn cèsuǒ zài nǎli',
    portuguese: 'com licenca, onde fica o banheiro?',
    gloss: 'com licenca / banheiro / estar / onde',
    blank: '请问厕所___',
    blankAnswer: '在哪里',
    note: '在哪里 e o bloco movel: troque 厕所 por qualquer lugar que voce quer encontrar.',
  },
  {
    id: 'chunk-descansar',
    unitId: 'daily',
    hanzi: '我想休息',
    pinyin: 'wǒ xiǎng xiūxi',
    portuguese: 'quero descansar',
    gloss: 'eu / querer / descansar',
    blank: '我想___',
    blankAnswer: '休息',
    note: '想 + verbo deixa a frase util para desejos simples sem soar seco demais.',
  },
  {
    id: 'chunk-quem-e-ele',
    unitId: 'people',
    hanzi: '他是谁',
    pinyin: 'tā shì shéi',
    portuguese: 'quem e ele?',
    gloss: 'ele / ser / quem',
    blank: '他是___',
    blankAnswer: '谁',
    note: '谁 substitui a pessoa desconhecida e fecha perguntas sobre identidade.',
  },
  {
    id: 'chunk-sou-estudante',
    unitId: 'people',
    hanzi: '我是学生',
    pinyin: 'wǒ shì xuésheng',
    portuguese: 'eu sou estudante',
    gloss: 'eu / ser / estudante',
    blank: '我是___',
    blankAnswer: '学生',
    note: 'Sou + papel social: troque 学生 por 老师 para mudar a frase.',
  },
  {
    id: 'chunk-falo-chines',
    unitId: 'school',
    hanzi: '我会说中文',
    pinyin: 'wǒ huì shuō Zhōngwén',
    portuguese: 'eu sei falar chines',
    gloss: 'eu / habilidade / falar / chines',
    blank: '我会___中文',
    blankAnswer: '说',
    note: '会 + verbo marca habilidade. Aqui, a habilidade e falar.',
  },
  {
    id: 'chunk-meu-livro',
    unitId: 'school',
    hanzi: '这是我的书',
    pinyin: 'zhè shì wǒ de shū',
    portuguese: 'este e meu livro',
    gloss: 'isto / ser / meu / livro',
    blank: '这是我的___',
    blankAnswer: '书',
    note: '这是 apresenta objetos. O final troca pelo objeto que voce quer mostrar.',
  },
  {
    id: 'chunk-vou-escola',
    unitId: 'city',
    hanzi: '我去学校',
    pinyin: 'wǒ qù xuéxiào',
    portuguese: 'eu vou para a escola',
    gloss: 'eu / ir / escola',
    blank: '我___学校',
    blankAnswer: '去',
    note: '去 + destino e uma das estruturas mais produtivas do HSK1.',
  },
  {
    id: 'chunk-taxi',
    unitId: 'city',
    hanzi: '我坐出租车',
    pinyin: 'wǒ zuò chūzūchē',
    portuguese: 'eu vou de taxi',
    gloss: 'eu / pegar / taxi',
    blank: '我___出租车',
    blankAnswer: '坐',
    note: '坐 tambem aparece com trem, aviao e onibus: sentar/pegar transporte.',
  },
  {
    id: 'chunk-comprar-fruta',
    unitId: 'city',
    hanzi: '我要买水果',
    pinyin: 'wǒ yào mǎi shuǐguǒ',
    portuguese: 'eu quero comprar frutas',
    gloss: 'eu / querer / comprar / fruta',
    blank: '我要___水果',
    blankAnswer: '买',
    note: '要 + 买 cria pedido direto para comprar algo.',
  },
  {
    id: 'chunk-hoje-segunda',
    unitId: 'sky',
    hanzi: '今天星期一',
    pinyin: 'jīntiān xīngqī yī',
    portuguese: 'hoje e segunda-feira',
    gloss: 'hoje / semana / um',
    blank: '今天___一',
    blankAnswer: '星期',
    note: '星期 + numero forma os dias da semana.',
  },
  {
    id: 'chunk-um-pouco-chines',
    unitId: 'sky',
    hanzi: '我会说一点中文',
    pinyin: 'wǒ huì shuō yìdiǎn Zhōngwén',
    portuguese: 'eu sei falar um pouco de chines',
    gloss: 'eu / saber / falar / um pouco / chines',
    blank: '我会说___中文',
    blankAnswer: '一点',
    note: '一点 reduz a pressao da frase: um pouco, nao perfeitamente.',
  },
  {
    id: 'chunk-qual-nome',
    unitId: 'hsk1-gate',
    hanzi: '你叫什么名字',
    pinyin: 'nǐ jiào shénme míngzi',
    portuguese: 'qual e o seu nome?',
    gloss: 'voce / chamar / que / nome',
    blank: '你叫什么___',
    blankAnswer: '名字',
    note: '叫什么名字 e pergunta inteira de checkpoint HSK1.',
  },
  {
    id: 'chunk-onde-mora',
    unitId: 'hsk1-gate',
    hanzi: '你住在哪儿',
    pinyin: 'nǐ zhù zài nǎr',
    portuguese: 'onde voce mora?',
    gloss: 'voce / morar / em / onde',
    blank: '你住在___',
    blankAnswer: '哪儿',
    note: '哪儿 e uma forma curta e comum de perguntar onde.',
  },
]
